package com.kd.ci.infrastructure.persistence.mapper.first;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.kd.ci.domain.first.Act;
import com.kd.ci.domain.first.ActExample;

public interface ActMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    @SelectProvider(type=ActSqlProvider.class, method="countByExample")
    long countByExample(ActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    @DeleteProvider(type=ActSqlProvider.class, method="deleteByExample")
    int deleteByExample(ActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    @Delete({
        "delete from Act",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    @Insert({
        "insert into Act (id, chiName, ",
        "actType, name, ",
        "level, t_APModifyDate, ",
        "t_APMotifier, t_APMotifierIP, ",
        "t_ReceiveDate, t_ReceiveSystem, ",
        "t_CreateDate, t_Creator, ",
        "t_CreatorIP, t_ModifyDate, ",
        "t_Modifier, t_ModifierIP)",
        "values (#{id,jdbcType=NUMERIC}, #{chiname,jdbcType=NVARCHAR}, ",
        "#{acttype,jdbcType=INTEGER}, #{name,jdbcType=NVARCHAR}, ",
        "#{level,jdbcType=INTEGER}, #{tApmodifydate,jdbcType=TIMESTAMP}, ",
        "#{tApmotifier,jdbcType=NVARCHAR}, #{tApmotifierip,jdbcType=NVARCHAR}, ",
        "#{tReceivedate,jdbcType=TIMESTAMP}, #{tReceivesystem,jdbcType=NVARCHAR}, ",
        "#{tCreatedate,jdbcType=TIMESTAMP}, #{tCreator,jdbcType=NVARCHAR}, ",
        "#{tCreatorip,jdbcType=NVARCHAR}, #{tModifydate,jdbcType=TIMESTAMP}, ",
        "#{tModifier,jdbcType=NVARCHAR}, #{tModifierip,jdbcType=NVARCHAR})"
    })
    int insert(Act row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    @InsertProvider(type=ActSqlProvider.class, method="insertSelective")
    int insertSelective(Act row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    @SelectProvider(type=ActSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="chiName", property="chiname", jdbcType=JdbcType.NVARCHAR),
        @Result(column="actType", property="acttype", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.NVARCHAR),
        @Result(column="level", property="level", jdbcType=JdbcType.INTEGER),
        @Result(column="t_APModifyDate", property="tApmodifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_APMotifier", property="tApmotifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_APMotifierIP", property="tApmotifierip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ReceiveDate", property="tReceivedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_ReceiveSystem", property="tReceivesystem", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreateDate", property="tCreatedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Creator", property="tCreator", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreatorIP", property="tCreatorip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifyDate", property="tModifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Modifier", property="tModifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifierIP", property="tModifierip", jdbcType=JdbcType.NVARCHAR)
    })
    List<Act> selectByExample(ActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    @Select({
        "select",
        "id, chiName, actType, name, level, t_APModifyDate, t_APMotifier, t_APMotifierIP, ",
        "t_ReceiveDate, t_ReceiveSystem, t_CreateDate, t_Creator, t_CreatorIP, t_ModifyDate, ",
        "t_Modifier, t_ModifierIP",
        "from Act",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="chiName", property="chiname", jdbcType=JdbcType.NVARCHAR),
        @Result(column="actType", property="acttype", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.NVARCHAR),
        @Result(column="level", property="level", jdbcType=JdbcType.INTEGER),
        @Result(column="t_APModifyDate", property="tApmodifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_APMotifier", property="tApmotifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_APMotifierIP", property="tApmotifierip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ReceiveDate", property="tReceivedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_ReceiveSystem", property="tReceivesystem", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreateDate", property="tCreatedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Creator", property="tCreator", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreatorIP", property="tCreatorip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifyDate", property="tModifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Modifier", property="tModifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifierIP", property="tModifierip", jdbcType=JdbcType.NVARCHAR)
    })
    Act selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    @UpdateProvider(type=ActSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") Act row, @Param("example") ActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    @UpdateProvider(type=ActSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") Act row, @Param("example") ActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    @UpdateProvider(type=ActSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Act row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    @Update({
        "update Act",
        "set chiName = #{chiname,jdbcType=NVARCHAR},",
          "actType = #{acttype,jdbcType=INTEGER},",
          "name = #{name,jdbcType=NVARCHAR},",
          "level = #{level,jdbcType=INTEGER},",
          "t_APModifyDate = #{tApmodifydate,jdbcType=TIMESTAMP},",
          "t_APMotifier = #{tApmotifier,jdbcType=NVARCHAR},",
          "t_APMotifierIP = #{tApmotifierip,jdbcType=NVARCHAR},",
          "t_ReceiveDate = #{tReceivedate,jdbcType=TIMESTAMP},",
          "t_ReceiveSystem = #{tReceivesystem,jdbcType=NVARCHAR},",
          "t_CreateDate = #{tCreatedate,jdbcType=TIMESTAMP},",
          "t_Creator = #{tCreator,jdbcType=NVARCHAR},",
          "t_CreatorIP = #{tCreatorip,jdbcType=NVARCHAR},",
          "t_ModifyDate = #{tModifydate,jdbcType=TIMESTAMP},",
          "t_Modifier = #{tModifier,jdbcType=NVARCHAR},",
          "t_ModifierIP = #{tModifierip,jdbcType=NVARCHAR}",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(Act row);
}