package com.kd.ci.infrastructure.persistence.mapper.first;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.kd.ci.domain.first.Belong;
import com.kd.ci.domain.first.BelongExample;

public interface BelongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    @SelectProvider(type=BelongSqlProvider.class, method="countByExample")
    long countByExample(BelongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    @DeleteProvider(type=BelongSqlProvider.class, method="deleteByExample")
    int deleteByExample(BelongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    @Delete({
        "delete from Belong",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    @Insert({
        "insert into Belong (id, orgUnitId, ",
        "personnelId, belongType, ",
        "subOrgUnitId, t_APModifyDate, ",
        "t_APMotifier, t_APMotifierIP, ",
        "t_ReceiveDate, t_ReceiveSystem, ",
        "t_CreateDate, t_Creator, ",
        "t_CreatorIP, t_ModifyDate, ",
        "t_Modifier, t_ModifierIP)",
        "values (#{id,jdbcType=NUMERIC}, #{orgunitid,jdbcType=NUMERIC}, ",
        "#{personnelid,jdbcType=NUMERIC}, #{belongtype,jdbcType=INTEGER}, ",
        "#{suborgunitid,jdbcType=NUMERIC}, #{tApmodifydate,jdbcType=TIMESTAMP}, ",
        "#{tApmotifier,jdbcType=NVARCHAR}, #{tApmotifierip,jdbcType=NVARCHAR}, ",
        "#{tReceivedate,jdbcType=TIMESTAMP}, #{tReceivesystem,jdbcType=NVARCHAR}, ",
        "#{tCreatedate,jdbcType=TIMESTAMP}, #{tCreator,jdbcType=NVARCHAR}, ",
        "#{tCreatorip,jdbcType=NVARCHAR}, #{tModifydate,jdbcType=TIMESTAMP}, ",
        "#{tModifier,jdbcType=NVARCHAR}, #{tModifierip,jdbcType=NVARCHAR})"
    })
    int insert(Belong row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    @InsertProvider(type=BelongSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys = true, keyProperty = "id")
    int insertSelective(Belong row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    @SelectProvider(type=BelongSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="orgUnitId", property="orgunitid", jdbcType=JdbcType.NUMERIC),
        @Result(column="personnelId", property="personnelid", jdbcType=JdbcType.NUMERIC),
        @Result(column="belongType", property="belongtype", jdbcType=JdbcType.INTEGER),
        @Result(column="subOrgUnitId", property="suborgunitid", jdbcType=JdbcType.NUMERIC),
        @Result(column="t_APModifyDate", property="tApmodifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_APMotifier", property="tApmotifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_APMotifierIP", property="tApmotifierip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ReceiveDate", property="tReceivedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_ReceiveSystem", property="tReceivesystem", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreateDate", property="tCreatedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Creator", property="tCreator", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreatorIP", property="tCreatorip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifyDate", property="tModifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Modifier", property="tModifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifierIP", property="tModifierip", jdbcType=JdbcType.NVARCHAR)
    })
    List<Belong> selectByExample(BelongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    @Select({
        "select",
        "id, orgUnitId, personnelId, belongType, subOrgUnitId, t_APModifyDate, t_APMotifier, ",
        "t_APMotifierIP, t_ReceiveDate, t_ReceiveSystem, t_CreateDate, t_Creator, t_CreatorIP, ",
        "t_ModifyDate, t_Modifier, t_ModifierIP",
        "from Belong",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="orgUnitId", property="orgunitid", jdbcType=JdbcType.NUMERIC),
        @Result(column="personnelId", property="personnelid", jdbcType=JdbcType.NUMERIC),
        @Result(column="belongType", property="belongtype", jdbcType=JdbcType.INTEGER),
        @Result(column="subOrgUnitId", property="suborgunitid", jdbcType=JdbcType.NUMERIC),
        @Result(column="t_APModifyDate", property="tApmodifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_APMotifier", property="tApmotifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_APMotifierIP", property="tApmotifierip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ReceiveDate", property="tReceivedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_ReceiveSystem", property="tReceivesystem", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreateDate", property="tCreatedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Creator", property="tCreator", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreatorIP", property="tCreatorip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifyDate", property="tModifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Modifier", property="tModifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifierIP", property="tModifierip", jdbcType=JdbcType.NVARCHAR)
    })
    Belong selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    @UpdateProvider(type=BelongSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") Belong row, @Param("example") BelongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    @UpdateProvider(type=BelongSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") Belong row, @Param("example") BelongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    @UpdateProvider(type=BelongSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Belong row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    @Update({
        "update Belong",
        "set orgUnitId = #{orgunitid,jdbcType=NUMERIC},",
          "personnelId = #{personnelid,jdbcType=NUMERIC},",
          "belongType = #{belongtype,jdbcType=INTEGER},",
          "subOrgUnitId = #{suborgunitid,jdbcType=NUMERIC},",
          "t_APModifyDate = #{tApmodifydate,jdbcType=TIMESTAMP},",
          "t_APMotifier = #{tApmotifier,jdbcType=NVARCHAR},",
          "t_APMotifierIP = #{tApmotifierip,jdbcType=NVARCHAR},",
          "t_ReceiveDate = #{tReceivedate,jdbcType=TIMESTAMP},",
          "t_ReceiveSystem = #{tReceivesystem,jdbcType=NVARCHAR},",
          "t_CreateDate = #{tCreatedate,jdbcType=TIMESTAMP},",
          "t_Creator = #{tCreator,jdbcType=NVARCHAR},",
          "t_CreatorIP = #{tCreatorip,jdbcType=NVARCHAR},",
          "t_ModifyDate = #{tModifydate,jdbcType=TIMESTAMP},",
          "t_Modifier = #{tModifier,jdbcType=NVARCHAR},",
          "t_ModifierIP = #{tModifierip,jdbcType=NVARCHAR}",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(Belong row);

    @Select("SELECT * " +
    		"FROM Belong " +
    		"WHERE personnelId = #{personnelId} ")
	Belong findBelongByPersonnelId(BigDecimal personnelId);

}