package com.kd.ci.infrastructure.persistence.mapper.first;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.jdbc.SQL;

import com.kd.ci.domain.first.Belong;
import com.kd.ci.domain.first.BelongExample;
import com.kd.ci.domain.first.BelongExample.Criteria;
import com.kd.ci.domain.first.BelongExample.Criterion;

public class BelongSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public String countByExample(BelongExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("Belong");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public String deleteByExample(BelongExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("Belong");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public String insertSelective(Belong row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("Belong");
        
        if (row.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=NUMERIC}");
        }
        
        if (row.getOrgunitid() != null) {
            sql.VALUES("orgUnitId", "#{orgunitid,jdbcType=NUMERIC}");
        }
        
        if (row.getPersonnelid() != null) {
            sql.VALUES("personnelId", "#{personnelid,jdbcType=NUMERIC}");
        }
        
        if (row.getBelongtype() != null) {
            sql.VALUES("belongType", "#{belongtype,jdbcType=INTEGER}");
        }
        
        if (row.getSuborgunitid() != null) {
            sql.VALUES("subOrgUnitId", "#{suborgunitid,jdbcType=NUMERIC}");
        }
        
        if (row.gettApmodifydate() != null) {
            sql.VALUES("t_APModifyDate", "#{tApmodifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettApmotifier() != null) {
            sql.VALUES("t_APMotifier", "#{tApmotifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettApmotifierip() != null) {
            sql.VALUES("t_APMotifierIP", "#{tApmotifierip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettReceivedate() != null) {
            sql.VALUES("t_ReceiveDate", "#{tReceivedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettReceivesystem() != null) {
            sql.VALUES("t_ReceiveSystem", "#{tReceivesystem,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreatedate() != null) {
            sql.VALUES("t_CreateDate", "#{tCreatedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettCreator() != null) {
            sql.VALUES("t_Creator", "#{tCreator,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreatorip() != null) {
            sql.VALUES("t_CreatorIP", "#{tCreatorip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifydate() != null) {
            sql.VALUES("t_ModifyDate", "#{tModifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettModifier() != null) {
            sql.VALUES("t_Modifier", "#{tModifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifierip() != null) {
            sql.VALUES("t_ModifierIP", "#{tModifierip,jdbcType=NVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public String selectByExample(BelongExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("orgUnitId");
        sql.SELECT("personnelId");
        sql.SELECT("belongType");
        sql.SELECT("subOrgUnitId");
        sql.SELECT("t_APModifyDate");
        sql.SELECT("t_APMotifier");
        sql.SELECT("t_APMotifierIP");
        sql.SELECT("t_ReceiveDate");
        sql.SELECT("t_ReceiveSystem");
        sql.SELECT("t_CreateDate");
        sql.SELECT("t_Creator");
        sql.SELECT("t_CreatorIP");
        sql.SELECT("t_ModifyDate");
        sql.SELECT("t_Modifier");
        sql.SELECT("t_ModifierIP");
        sql.FROM("Belong");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Belong row = (Belong) parameter.get("row");
        BelongExample example = (BelongExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("Belong");
        
        if (row.getId() != null) {
            sql.SET("id = #{row.id,jdbcType=NUMERIC}");
        }
        
        if (row.getOrgunitid() != null) {
            sql.SET("orgUnitId = #{row.orgunitid,jdbcType=NUMERIC}");
        }
        
        if (row.getPersonnelid() != null) {
            sql.SET("personnelId = #{row.personnelid,jdbcType=NUMERIC}");
        }
        
        if (row.getBelongtype() != null) {
            sql.SET("belongType = #{row.belongtype,jdbcType=INTEGER}");
        }
        
        if (row.getSuborgunitid() != null) {
            sql.SET("subOrgUnitId = #{row.suborgunitid,jdbcType=NUMERIC}");
        }
        
        if (row.gettApmodifydate() != null) {
            sql.SET("t_APModifyDate = #{row.tApmodifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettApmotifier() != null) {
            sql.SET("t_APMotifier = #{row.tApmotifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettApmotifierip() != null) {
            sql.SET("t_APMotifierIP = #{row.tApmotifierip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettReceivedate() != null) {
            sql.SET("t_ReceiveDate = #{row.tReceivedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettReceivesystem() != null) {
            sql.SET("t_ReceiveSystem = #{row.tReceivesystem,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreatedate() != null) {
            sql.SET("t_CreateDate = #{row.tCreatedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettCreator() != null) {
            sql.SET("t_Creator = #{row.tCreator,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreatorip() != null) {
            sql.SET("t_CreatorIP = #{row.tCreatorip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifydate() != null) {
            sql.SET("t_ModifyDate = #{row.tModifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettModifier() != null) {
            sql.SET("t_Modifier = #{row.tModifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifierip() != null) {
            sql.SET("t_ModifierIP = #{row.tModifierip,jdbcType=NVARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("Belong");
        
        sql.SET("id = #{row.id,jdbcType=NUMERIC}");
        sql.SET("orgUnitId = #{row.orgunitid,jdbcType=NUMERIC}");
        sql.SET("personnelId = #{row.personnelid,jdbcType=NUMERIC}");
        sql.SET("belongType = #{row.belongtype,jdbcType=INTEGER}");
        sql.SET("subOrgUnitId = #{row.suborgunitid,jdbcType=NUMERIC}");
        sql.SET("t_APModifyDate = #{row.tApmodifydate,jdbcType=TIMESTAMP}");
        sql.SET("t_APMotifier = #{row.tApmotifier,jdbcType=NVARCHAR}");
        sql.SET("t_APMotifierIP = #{row.tApmotifierip,jdbcType=NVARCHAR}");
        sql.SET("t_ReceiveDate = #{row.tReceivedate,jdbcType=TIMESTAMP}");
        sql.SET("t_ReceiveSystem = #{row.tReceivesystem,jdbcType=NVARCHAR}");
        sql.SET("t_CreateDate = #{row.tCreatedate,jdbcType=TIMESTAMP}");
        sql.SET("t_Creator = #{row.tCreator,jdbcType=NVARCHAR}");
        sql.SET("t_CreatorIP = #{row.tCreatorip,jdbcType=NVARCHAR}");
        sql.SET("t_ModifyDate = #{row.tModifydate,jdbcType=TIMESTAMP}");
        sql.SET("t_Modifier = #{row.tModifier,jdbcType=NVARCHAR}");
        sql.SET("t_ModifierIP = #{row.tModifierip,jdbcType=NVARCHAR}");
        
        BelongExample example = (BelongExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public String updateByPrimaryKeySelective(Belong row) {
        SQL sql = new SQL();
        sql.UPDATE("Belong");
        
        if (row.getOrgunitid() != null) {
            sql.SET("orgUnitId = #{orgunitid,jdbcType=NUMERIC}");
        }
        
        if (row.getPersonnelid() != null) {
            sql.SET("personnelId = #{personnelid,jdbcType=NUMERIC}");
        }
        
        if (row.getBelongtype() != null) {
            sql.SET("belongType = #{belongtype,jdbcType=INTEGER}");
        }
        
        if (row.getSuborgunitid() != null) {
            sql.SET("subOrgUnitId = #{suborgunitid,jdbcType=NUMERIC}");
        }
        
        if (row.gettApmodifydate() != null) {
            sql.SET("t_APModifyDate = #{tApmodifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettApmotifier() != null) {
            sql.SET("t_APMotifier = #{tApmotifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettApmotifierip() != null) {
            sql.SET("t_APMotifierIP = #{tApmotifierip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettReceivedate() != null) {
            sql.SET("t_ReceiveDate = #{tReceivedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettReceivesystem() != null) {
            sql.SET("t_ReceiveSystem = #{tReceivesystem,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreatedate() != null) {
            sql.SET("t_CreateDate = #{tCreatedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettCreator() != null) {
            sql.SET("t_Creator = #{tCreator,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreatorip() != null) {
            sql.SET("t_CreatorIP = #{tCreatorip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifydate() != null) {
            sql.SET("t_ModifyDate = #{tModifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettModifier() != null) {
            sql.SET("t_Modifier = #{tModifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifierip() != null) {
            sql.SET("t_ModifierIP = #{tModifierip,jdbcType=NVARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=NUMERIC}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    protected void applyWhere(SQL sql, BelongExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}