package com.kd.ci.infrastructure.persistence.mapper.first;

import java.util.List;

import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.kd.ci.domain.first.BelongAct;
import com.kd.ci.domain.first.BelongActExample;

public interface BelongActMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong_Act
     *
     * @mbg.generated Mon Apr 28 12:01:12 CST 2025
     */
    @SelectProvider(type=BelongActSqlProvider.class, method="countByExample")
    long countByExample(BelongActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong_Act
     *
     * @mbg.generated Mon Apr 28 12:01:12 CST 2025
     */
    @DeleteProvider(type=BelongActSqlProvider.class, method="deleteByExample")
    int deleteByExample(BelongActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong_Act
     *
     * @mbg.generated Mon Apr 28 12:01:12 CST 2025
     */
    @Insert({
        "insert into Belong_Act (Belong_id, acts_id, ",
        "t_APModifyDate, t_APMotifier, ",
        "t_APMotifierIP, t_ReceiveDate, ",
        "t_ReceiveSystem, t_CreateDate, ",
        "t_Creator, t_CreatorIP, ",
        "t_ModifyDate, t_Modifier, ",
        "t_ModifierIP)",
        "values (#{belongId,jdbcType=NUMERIC}, #{actsId,jdbcType=NUMERIC}, ",
        "#{tApmodifydate,jdbcType=TIMESTAMP}, #{tApmotifier,jdbcType=NVARCHAR}, ",
        "#{tApmotifierip,jdbcType=NVARCHAR}, #{tReceivedate,jdbcType=TIMESTAMP}, ",
        "#{tReceivesystem,jdbcType=NVARCHAR}, #{tCreatedate,jdbcType=TIMESTAMP}, ",
        "#{tCreator,jdbcType=NVARCHAR}, #{tCreatorip,jdbcType=NVARCHAR}, ",
        "#{tModifydate,jdbcType=TIMESTAMP}, #{tModifier,jdbcType=NVARCHAR}, ",
        "#{tModifierip,jdbcType=NVARCHAR})"
    })
    int insert(BelongAct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong_Act
     *
     * @mbg.generated Mon Apr 28 12:01:12 CST 2025
     */
    @InsertProvider(type=BelongActSqlProvider.class, method="insertSelective")
    int insertSelective(BelongAct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong_Act
     *
     * @mbg.generated Mon Apr 28 12:01:12 CST 2025
     */
    @SelectProvider(type=BelongActSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="Belong_id", property="belongId", jdbcType=JdbcType.NUMERIC),
        @Result(column="acts_id", property="actsId", jdbcType=JdbcType.NUMERIC),
        @Result(column="t_APModifyDate", property="tApmodifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_APMotifier", property="tApmotifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_APMotifierIP", property="tApmotifierip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ReceiveDate", property="tReceivedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_ReceiveSystem", property="tReceivesystem", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreateDate", property="tCreatedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Creator", property="tCreator", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreatorIP", property="tCreatorip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifyDate", property="tModifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Modifier", property="tModifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifierIP", property="tModifierip", jdbcType=JdbcType.NVARCHAR)
    })
    List<BelongAct> selectByExample(BelongActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong_Act
     *
     * @mbg.generated Mon Apr 28 12:01:12 CST 2025
     */
    @UpdateProvider(type=BelongActSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") BelongAct row, @Param("example") BelongActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Belong_Act
     *
     * @mbg.generated Mon Apr 28 12:01:12 CST 2025
     */
    @UpdateProvider(type=BelongActSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") BelongAct row, @Param("example") BelongActExample example);
    
    /**
     * 批次插入 BelongAct
     * Lang(RawLanguageDriver.class)，告訴 MyBatis annotation 允許使用完整的 <script> 標籤語法。
     */
    @Insert({
        "<script>",
        "INSERT INTO Belong_Act ",
        "(",
        "Belong_id, acts_id, t_APModifyDate, t_APMotifier, t_APMotifierIP,",
        "t_ReceiveDate, t_ReceiveSystem, t_CreateDate, t_Creator, t_CreatorIP,",
        "t_ModifyDate, t_Modifier, t_ModifierIP",
        ") VALUES ",
        "<foreach collection='list' item='item' separator=','>",
        "(",
        "#{item.belongId,jdbcType=NUMERIC},",
        "#{item.actsId,jdbcType=NUMERIC},",
        "#{item.tApmodifydate,jdbcType=TIMESTAMP},",
        "#{item.tApmotifier,jdbcType=NVARCHAR},",
        "#{item.tApmotifierip,jdbcType=NVARCHAR},",
        "#{item.tReceivedate,jdbcType=TIMESTAMP},",
        "#{item.tReceivesystem,jdbcType=NVARCHAR},",
        "#{item.tCreatedate,jdbcType=TIMESTAMP},",
        "#{item.tCreator,jdbcType=NVARCHAR},",
        "#{item.tCreatorip,jdbcType=NVARCHAR},",
        "#{item.tModifydate,jdbcType=TIMESTAMP},",
        "#{item.tModifier,jdbcType=NVARCHAR},",
        "#{item.tModifierip,jdbcType=NVARCHAR}",
        ")",
        "</foreach>",
        "</script>"
    })
    int insertBatch(@Param("list") List<BelongAct> list);
}