package com.kd.ci.infrastructure.persistence.mapper.first;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.kd.ci.domain.first.Menuitem;
import com.kd.ci.domain.first.MenuitemExample;

public interface MenuitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MenuItem
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    @SelectProvider(type=MenuitemSqlProvider.class, method="countByExample")
    long countByExample(MenuitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MenuItem
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    @DeleteProvider(type=MenuitemSqlProvider.class, method="deleteByExample")
    int deleteByExample(MenuitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MenuItem
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    @Delete({
        "delete from MenuItem",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MenuItem
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    @Insert({
        "insert into MenuItem (id, toolTip, ",
        "name, location, ",
        "title, position, ",
        "align, action, ",
        "parent_id, t_APModifyDate, ",
        "t_APMotifier, t_APMotifierIP, ",
        "t_ReceiveDate, t_ReceiveSystem, ",
        "t_CreateDate, t_Creator, ",
        "t_CreatorIP, t_ModifyDate, ",
        "t_Modifier, t_ModifierIP)",
        "values (#{id,jdbcType=NUMERIC}, #{tooltip,jdbcType=NVARCHAR}, ",
        "#{name,jdbcType=NVARCHAR}, #{location,jdbcType=VARCHAR}, ",
        "#{title,jdbcType=NVARCHAR}, #{position,jdbcType=NUMERIC}, ",
        "#{align,jdbcType=NVARCHAR}, #{action,jdbcType=VARCHAR}, ",
        "#{parentId,jdbcType=NUMERIC}, #{tApmodifydate,jdbcType=TIMESTAMP}, ",
        "#{tApmotifier,jdbcType=NVARCHAR}, #{tApmotifierip,jdbcType=NVARCHAR}, ",
        "#{tReceivedate,jdbcType=TIMESTAMP}, #{tReceivesystem,jdbcType=NVARCHAR}, ",
        "#{tCreatedate,jdbcType=TIMESTAMP}, #{tCreator,jdbcType=NVARCHAR}, ",
        "#{tCreatorip,jdbcType=NVARCHAR}, #{tModifydate,jdbcType=TIMESTAMP}, ",
        "#{tModifier,jdbcType=NVARCHAR}, #{tModifierip,jdbcType=NVARCHAR})"
    })
    int insert(Menuitem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MenuItem
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    @InsertProvider(type=MenuitemSqlProvider.class, method="insertSelective")
    int insertSelective(Menuitem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MenuItem
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    @SelectProvider(type=MenuitemSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="toolTip", property="tooltip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.NVARCHAR),
        @Result(column="location", property="location", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.NVARCHAR),
        @Result(column="position", property="position", jdbcType=JdbcType.NUMERIC),
        @Result(column="align", property="align", jdbcType=JdbcType.NVARCHAR),
        @Result(column="action", property="action", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.NUMERIC),
        @Result(column="t_APModifyDate", property="tApmodifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_APMotifier", property="tApmotifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_APMotifierIP", property="tApmotifierip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ReceiveDate", property="tReceivedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_ReceiveSystem", property="tReceivesystem", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreateDate", property="tCreatedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Creator", property="tCreator", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreatorIP", property="tCreatorip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifyDate", property="tModifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Modifier", property="tModifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifierIP", property="tModifierip", jdbcType=JdbcType.NVARCHAR)
    })
    List<Menuitem> selectByExample(MenuitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MenuItem
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    @Select({
        "select",
        "id, toolTip, name, location, title, position, align, action, parent_id, t_APModifyDate, ",
        "t_APMotifier, t_APMotifierIP, t_ReceiveDate, t_ReceiveSystem, t_CreateDate, ",
        "t_Creator, t_CreatorIP, t_ModifyDate, t_Modifier, t_ModifierIP",
        "from MenuItem",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="toolTip", property="tooltip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.NVARCHAR),
        @Result(column="location", property="location", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.NVARCHAR),
        @Result(column="position", property="position", jdbcType=JdbcType.NUMERIC),
        @Result(column="align", property="align", jdbcType=JdbcType.NVARCHAR),
        @Result(column="action", property="action", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.NUMERIC),
        @Result(column="t_APModifyDate", property="tApmodifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_APMotifier", property="tApmotifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_APMotifierIP", property="tApmotifierip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ReceiveDate", property="tReceivedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_ReceiveSystem", property="tReceivesystem", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreateDate", property="tCreatedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Creator", property="tCreator", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreatorIP", property="tCreatorip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifyDate", property="tModifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Modifier", property="tModifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifierIP", property="tModifierip", jdbcType=JdbcType.NVARCHAR)
    })
    Menuitem selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MenuItem
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    @UpdateProvider(type=MenuitemSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") Menuitem row, @Param("example") MenuitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MenuItem
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    @UpdateProvider(type=MenuitemSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") Menuitem row, @Param("example") MenuitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MenuItem
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    @UpdateProvider(type=MenuitemSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Menuitem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MenuItem
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    @Update({
        "update MenuItem",
        "set toolTip = #{tooltip,jdbcType=NVARCHAR},",
          "name = #{name,jdbcType=NVARCHAR},",
          "location = #{location,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=NVARCHAR},",
          "position = #{position,jdbcType=NUMERIC},",
          "align = #{align,jdbcType=NVARCHAR},",
          "action = #{action,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=NUMERIC},",
          "t_APModifyDate = #{tApmodifydate,jdbcType=TIMESTAMP},",
          "t_APMotifier = #{tApmotifier,jdbcType=NVARCHAR},",
          "t_APMotifierIP = #{tApmotifierip,jdbcType=NVARCHAR},",
          "t_ReceiveDate = #{tReceivedate,jdbcType=TIMESTAMP},",
          "t_ReceiveSystem = #{tReceivesystem,jdbcType=NVARCHAR},",
          "t_CreateDate = #{tCreatedate,jdbcType=TIMESTAMP},",
          "t_Creator = #{tCreator,jdbcType=NVARCHAR},",
          "t_CreatorIP = #{tCreatorip,jdbcType=NVARCHAR},",
          "t_ModifyDate = #{tModifydate,jdbcType=TIMESTAMP},",
          "t_Modifier = #{tModifier,jdbcType=NVARCHAR},",
          "t_ModifierIP = #{tModifierip,jdbcType=NVARCHAR}",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(Menuitem row);
    
    @Select({
		"<script>",
		"SELECT distinct mi.* ",
		"FROM Act_MenuItem ami ",
		"JOIN MenuItem mi ON ami.menuItems_id = mi.id ",
		"WHERE ami.acts_id IN ",
		"<foreach item='item' index='index' collection='actsIds' open='(' separator=',' close=')'>",
		"#{item}",
		"</foreach>",
		"</script>"
	})
	List<Menuitem> findMenuItemsByActsIds(List<BigDecimal> actsIds);
    
    @Select("SELECT c.* " +
    		"FROM Act a, Act_MenuItem b, MenuItem c " +
    		"WHERE a.id = b.acts_id " +
    		"AND b.menuItems_id = c.id " +
    		"AND a.id = #{actId}")
    List<Menuitem> findMenuItemsByActId(@Param("actId") BigDecimal actId);
}