package com.kd.ci.infrastructure.persistence.mapper.first;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.jdbc.SQL;

import com.kd.ci.domain.first.Orgunit;
import com.kd.ci.domain.first.OrgunitExample;
import com.kd.ci.domain.first.OrgunitExample.Criteria;
import com.kd.ci.domain.first.OrgunitExample.Criterion;

public class OrgunitSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    public String countByExample(OrgunitExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("OrgUnit");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    public String deleteByExample(OrgunitExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("OrgUnit");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    public String insertSelective(Orgunit row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("OrgUnit");
        
        if (row.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=NUMERIC}");
        }
        
        if (row.getOrgcode() != null) {
            sql.VALUES("orgCode", "#{orgcode,jdbcType=VARCHAR}");
        }
        
        if (row.getShortname() != null) {
            sql.VALUES("shortName", "#{shortname,jdbcType=NVARCHAR}");
        }
        
        if (row.getFullname() != null) {
            sql.VALUES("fullName", "#{fullname,jdbcType=NVARCHAR}");
        }
        
        if (row.getDepno() != null) {
            sql.VALUES("depNo", "#{depno,jdbcType=VARCHAR}");
        }
        
        if (row.getUnittype() != null) {
            sql.VALUES("unitType", "#{unittype,jdbcType=INTEGER}");
        }
        
        if (row.getTel() != null) {
            sql.VALUES("tel", "#{tel,jdbcType=VARCHAR}");
        }
        
        if (row.getFax() != null) {
            sql.VALUES("fax", "#{fax,jdbcType=VARCHAR}");
        }
        
        if (row.getAddr() != null) {
            sql.VALUES("addr", "#{addr,jdbcType=NVARCHAR}");
        }
        
        if (row.getBossid() != null) {
            sql.VALUES("bossId", "#{bossid,jdbcType=NUMERIC}");
        }
        
        if (row.getOnline() != null) {
            sql.VALUES("onLine", "#{online,jdbcType=TINYINT}");
        }
        
        if (row.getSendevent() != null) {
            sql.VALUES("sendEvent", "#{sendevent,jdbcType=TINYINT}");
        }
        
        if (row.getParentid() != null) {
            sql.VALUES("parentId", "#{parentid,jdbcType=NUMERIC}");
        }
        
        if (row.getSection() != null) {
            sql.VALUES("section", "#{section,jdbcType=VARCHAR}");
        }
        
        if (row.getSequence() != null) {
            sql.VALUES("sequence", "#{sequence,jdbcType=INTEGER}");
        }
        
        if (row.getSentcaseid() != null) {
            sql.VALUES("sentCaseId", "#{sentcaseid,jdbcType=NUMERIC}");
        }
        
        if (row.gettApmodifydate() != null) {
            sql.VALUES("t_APModifyDate", "#{tApmodifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettApmotifier() != null) {
            sql.VALUES("t_APMotifier", "#{tApmotifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettApmotifierip() != null) {
            sql.VALUES("t_APMotifierIP", "#{tApmotifierip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettReceivedate() != null) {
            sql.VALUES("t_ReceiveDate", "#{tReceivedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettReceivesystem() != null) {
            sql.VALUES("t_ReceiveSystem", "#{tReceivesystem,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreatedate() != null) {
            sql.VALUES("t_CreateDate", "#{tCreatedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettCreator() != null) {
            sql.VALUES("t_Creator", "#{tCreator,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreatorip() != null) {
            sql.VALUES("t_CreatorIP", "#{tCreatorip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifydate() != null) {
            sql.VALUES("t_ModifyDate", "#{tModifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettModifier() != null) {
            sql.VALUES("t_Modifier", "#{tModifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifierip() != null) {
            sql.VALUES("t_ModifierIP", "#{tModifierip,jdbcType=NVARCHAR}");
        }
        
        if (row.getRefunitcode() != null) {
            sql.VALUES("refUnitCode", "#{refunitcode,jdbcType=NVARCHAR}");
        }
        
        if (row.getConsumerunitid() != null) {
            sql.VALUES("consumerUnitId", "#{consumerunitid,jdbcType=NUMERIC}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    public String selectByExample(OrgunitExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("orgCode");
        sql.SELECT("shortName");
        sql.SELECT("fullName");
        sql.SELECT("depNo");
        sql.SELECT("unitType");
        sql.SELECT("tel");
        sql.SELECT("fax");
        sql.SELECT("addr");
        sql.SELECT("bossId");
        sql.SELECT("onLine");
        sql.SELECT("sendEvent");
        sql.SELECT("parentId");
        sql.SELECT("section");
        sql.SELECT("sequence");
        sql.SELECT("sentCaseId");
        sql.SELECT("t_APModifyDate");
        sql.SELECT("t_APMotifier");
        sql.SELECT("t_APMotifierIP");
        sql.SELECT("t_ReceiveDate");
        sql.SELECT("t_ReceiveSystem");
        sql.SELECT("t_CreateDate");
        sql.SELECT("t_Creator");
        sql.SELECT("t_CreatorIP");
        sql.SELECT("t_ModifyDate");
        sql.SELECT("t_Modifier");
        sql.SELECT("t_ModifierIP");
        sql.SELECT("refUnitCode");
        sql.SELECT("consumerUnitId");
        sql.FROM("OrgUnit");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Orgunit row = (Orgunit) parameter.get("row");
        OrgunitExample example = (OrgunitExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("OrgUnit");
        
        if (row.getId() != null) {
            sql.SET("id = #{row.id,jdbcType=NUMERIC}");
        }
        
        if (row.getOrgcode() != null) {
            sql.SET("orgCode = #{row.orgcode,jdbcType=VARCHAR}");
        }
        
        if (row.getShortname() != null) {
            sql.SET("shortName = #{row.shortname,jdbcType=NVARCHAR}");
        }
        
        if (row.getFullname() != null) {
            sql.SET("fullName = #{row.fullname,jdbcType=NVARCHAR}");
        }
        
        if (row.getDepno() != null) {
            sql.SET("depNo = #{row.depno,jdbcType=VARCHAR}");
        }
        
        if (row.getUnittype() != null) {
            sql.SET("unitType = #{row.unittype,jdbcType=INTEGER}");
        }
        
        if (row.getTel() != null) {
            sql.SET("tel = #{row.tel,jdbcType=VARCHAR}");
        }
        
        if (row.getFax() != null) {
            sql.SET("fax = #{row.fax,jdbcType=VARCHAR}");
        }
        
        if (row.getAddr() != null) {
            sql.SET("addr = #{row.addr,jdbcType=NVARCHAR}");
        }
        
        if (row.getBossid() != null) {
            sql.SET("bossId = #{row.bossid,jdbcType=NUMERIC}");
        }
        
        if (row.getOnline() != null) {
            sql.SET("onLine = #{row.online,jdbcType=TINYINT}");
        }
        
        if (row.getSendevent() != null) {
            sql.SET("sendEvent = #{row.sendevent,jdbcType=TINYINT}");
        }
        
        if (row.getParentid() != null) {
            sql.SET("parentId = #{row.parentid,jdbcType=NUMERIC}");
        }
        
        if (row.getSection() != null) {
            sql.SET("section = #{row.section,jdbcType=VARCHAR}");
        }
        
        if (row.getSequence() != null) {
            sql.SET("sequence = #{row.sequence,jdbcType=INTEGER}");
        }
        
        if (row.getSentcaseid() != null) {
            sql.SET("sentCaseId = #{row.sentcaseid,jdbcType=NUMERIC}");
        }
        
        if (row.gettApmodifydate() != null) {
            sql.SET("t_APModifyDate = #{row.tApmodifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettApmotifier() != null) {
            sql.SET("t_APMotifier = #{row.tApmotifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettApmotifierip() != null) {
            sql.SET("t_APMotifierIP = #{row.tApmotifierip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettReceivedate() != null) {
            sql.SET("t_ReceiveDate = #{row.tReceivedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettReceivesystem() != null) {
            sql.SET("t_ReceiveSystem = #{row.tReceivesystem,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreatedate() != null) {
            sql.SET("t_CreateDate = #{row.tCreatedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettCreator() != null) {
            sql.SET("t_Creator = #{row.tCreator,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreatorip() != null) {
            sql.SET("t_CreatorIP = #{row.tCreatorip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifydate() != null) {
            sql.SET("t_ModifyDate = #{row.tModifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettModifier() != null) {
            sql.SET("t_Modifier = #{row.tModifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifierip() != null) {
            sql.SET("t_ModifierIP = #{row.tModifierip,jdbcType=NVARCHAR}");
        }
        
        if (row.getRefunitcode() != null) {
            sql.SET("refUnitCode = #{row.refunitcode,jdbcType=NVARCHAR}");
        }
        
        if (row.getConsumerunitid() != null) {
            sql.SET("consumerUnitId = #{row.consumerunitid,jdbcType=NUMERIC}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("OrgUnit");
        
        sql.SET("id = #{row.id,jdbcType=NUMERIC}");
        sql.SET("orgCode = #{row.orgcode,jdbcType=VARCHAR}");
        sql.SET("shortName = #{row.shortname,jdbcType=NVARCHAR}");
        sql.SET("fullName = #{row.fullname,jdbcType=NVARCHAR}");
        sql.SET("depNo = #{row.depno,jdbcType=VARCHAR}");
        sql.SET("unitType = #{row.unittype,jdbcType=INTEGER}");
        sql.SET("tel = #{row.tel,jdbcType=VARCHAR}");
        sql.SET("fax = #{row.fax,jdbcType=VARCHAR}");
        sql.SET("addr = #{row.addr,jdbcType=NVARCHAR}");
        sql.SET("bossId = #{row.bossid,jdbcType=NUMERIC}");
        sql.SET("onLine = #{row.online,jdbcType=TINYINT}");
        sql.SET("sendEvent = #{row.sendevent,jdbcType=TINYINT}");
        sql.SET("parentId = #{row.parentid,jdbcType=NUMERIC}");
        sql.SET("section = #{row.section,jdbcType=VARCHAR}");
        sql.SET("sequence = #{row.sequence,jdbcType=INTEGER}");
        sql.SET("sentCaseId = #{row.sentcaseid,jdbcType=NUMERIC}");
        sql.SET("t_APModifyDate = #{row.tApmodifydate,jdbcType=TIMESTAMP}");
        sql.SET("t_APMotifier = #{row.tApmotifier,jdbcType=NVARCHAR}");
        sql.SET("t_APMotifierIP = #{row.tApmotifierip,jdbcType=NVARCHAR}");
        sql.SET("t_ReceiveDate = #{row.tReceivedate,jdbcType=TIMESTAMP}");
        sql.SET("t_ReceiveSystem = #{row.tReceivesystem,jdbcType=NVARCHAR}");
        sql.SET("t_CreateDate = #{row.tCreatedate,jdbcType=TIMESTAMP}");
        sql.SET("t_Creator = #{row.tCreator,jdbcType=NVARCHAR}");
        sql.SET("t_CreatorIP = #{row.tCreatorip,jdbcType=NVARCHAR}");
        sql.SET("t_ModifyDate = #{row.tModifydate,jdbcType=TIMESTAMP}");
        sql.SET("t_Modifier = #{row.tModifier,jdbcType=NVARCHAR}");
        sql.SET("t_ModifierIP = #{row.tModifierip,jdbcType=NVARCHAR}");
        sql.SET("refUnitCode = #{row.refunitcode,jdbcType=NVARCHAR}");
        sql.SET("consumerUnitId = #{row.consumerunitid,jdbcType=NUMERIC}");
        
        OrgunitExample example = (OrgunitExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    public String updateByPrimaryKeySelective(Orgunit row) {
        SQL sql = new SQL();
        sql.UPDATE("OrgUnit");
        
        if (row.getOrgcode() != null) {
            sql.SET("orgCode = #{orgcode,jdbcType=VARCHAR}");
        }
        
        if (row.getShortname() != null) {
            sql.SET("shortName = #{shortname,jdbcType=NVARCHAR}");
        }
        
        if (row.getFullname() != null) {
            sql.SET("fullName = #{fullname,jdbcType=NVARCHAR}");
        }
        
        if (row.getDepno() != null) {
            sql.SET("depNo = #{depno,jdbcType=VARCHAR}");
        }
        
        if (row.getUnittype() != null) {
            sql.SET("unitType = #{unittype,jdbcType=INTEGER}");
        }
        
        if (row.getTel() != null) {
            sql.SET("tel = #{tel,jdbcType=VARCHAR}");
        }
        
        if (row.getFax() != null) {
            sql.SET("fax = #{fax,jdbcType=VARCHAR}");
        }
        
        if (row.getAddr() != null) {
            sql.SET("addr = #{addr,jdbcType=NVARCHAR}");
        }
        
        if (row.getBossid() != null) {
            sql.SET("bossId = #{bossid,jdbcType=NUMERIC}");
        }
        
        if (row.getOnline() != null) {
            sql.SET("onLine = #{online,jdbcType=TINYINT}");
        }
        
        if (row.getSendevent() != null) {
            sql.SET("sendEvent = #{sendevent,jdbcType=TINYINT}");
        }
        
        if (row.getParentid() != null) {
            sql.SET("parentId = #{parentid,jdbcType=NUMERIC}");
        }
        
        if (row.getSection() != null) {
            sql.SET("section = #{section,jdbcType=VARCHAR}");
        }
        
        if (row.getSequence() != null) {
            sql.SET("sequence = #{sequence,jdbcType=INTEGER}");
        }
        
        if (row.getSentcaseid() != null) {
            sql.SET("sentCaseId = #{sentcaseid,jdbcType=NUMERIC}");
        }
        
        if (row.gettApmodifydate() != null) {
            sql.SET("t_APModifyDate = #{tApmodifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettApmotifier() != null) {
            sql.SET("t_APMotifier = #{tApmotifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettApmotifierip() != null) {
            sql.SET("t_APMotifierIP = #{tApmotifierip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettReceivedate() != null) {
            sql.SET("t_ReceiveDate = #{tReceivedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettReceivesystem() != null) {
            sql.SET("t_ReceiveSystem = #{tReceivesystem,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreatedate() != null) {
            sql.SET("t_CreateDate = #{tCreatedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettCreator() != null) {
            sql.SET("t_Creator = #{tCreator,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreatorip() != null) {
            sql.SET("t_CreatorIP = #{tCreatorip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifydate() != null) {
            sql.SET("t_ModifyDate = #{tModifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettModifier() != null) {
            sql.SET("t_Modifier = #{tModifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifierip() != null) {
            sql.SET("t_ModifierIP = #{tModifierip,jdbcType=NVARCHAR}");
        }
        
        if (row.getRefunitcode() != null) {
            sql.SET("refUnitCode = #{refunitcode,jdbcType=NVARCHAR}");
        }
        
        if (row.getConsumerunitid() != null) {
            sql.SET("consumerUnitId = #{consumerunitid,jdbcType=NUMERIC}");
        }
        
        sql.WHERE("id = #{id,jdbcType=NUMERIC}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    protected void applyWhere(SQL sql, OrgunitExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}