package com.kd.ci.infrastructure.persistence.mapper.first;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.kd.ci.domain.first.Orgunit;
import com.kd.ci.domain.first.OrgunitExample;
import com.kd.ci.domain.first.OrgunitWithBelong;

public interface OrgunitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    @SelectProvider(type=OrgunitSqlProvider.class, method="countByExample")
    long countByExample(OrgunitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    @DeleteProvider(type=OrgunitSqlProvider.class, method="deleteByExample")
    int deleteByExample(OrgunitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    @Delete({
        "delete from OrgUnit",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    @Insert({
        "insert into OrgUnit (id, orgCode, ",
        "shortName, fullName, ",
        "depNo, unitType, ",
        "tel, fax, addr, ",
        "bossId, onLine, ",
        "sendEvent, parentId, ",
        "section, sequence, ",
        "sentCaseId, t_APModifyDate, ",
        "t_APMotifier, t_APMotifierIP, ",
        "t_ReceiveDate, t_ReceiveSystem, ",
        "t_CreateDate, t_Creator, ",
        "t_CreatorIP, t_ModifyDate, ",
        "t_Modifier, t_ModifierIP, ",
        "refUnitCode, consumerUnitId)",
        "values (#{id,jdbcType=NUMERIC}, #{orgcode,jdbcType=VARCHAR}, ",
        "#{shortname,jdbcType=NVARCHAR}, #{fullname,jdbcType=NVARCHAR}, ",
        "#{depno,jdbcType=VARCHAR}, #{unittype,jdbcType=INTEGER}, ",
        "#{tel,jdbcType=VARCHAR}, #{fax,jdbcType=VARCHAR}, #{addr,jdbcType=NVARCHAR}, ",
        "#{bossid,jdbcType=NUMERIC}, #{online,jdbcType=TINYINT}, ",
        "#{sendevent,jdbcType=TINYINT}, #{parentid,jdbcType=NUMERIC}, ",
        "#{section,jdbcType=VARCHAR}, #{sequence,jdbcType=INTEGER}, ",
        "#{sentcaseid,jdbcType=NUMERIC}, #{tApmodifydate,jdbcType=TIMESTAMP}, ",
        "#{tApmotifier,jdbcType=NVARCHAR}, #{tApmotifierip,jdbcType=NVARCHAR}, ",
        "#{tReceivedate,jdbcType=TIMESTAMP}, #{tReceivesystem,jdbcType=NVARCHAR}, ",
        "#{tCreatedate,jdbcType=TIMESTAMP}, #{tCreator,jdbcType=NVARCHAR}, ",
        "#{tCreatorip,jdbcType=NVARCHAR}, #{tModifydate,jdbcType=TIMESTAMP}, ",
        "#{tModifier,jdbcType=NVARCHAR}, #{tModifierip,jdbcType=NVARCHAR}, ",
        "#{refunitcode,jdbcType=NVARCHAR}, #{consumerunitid,jdbcType=NUMERIC})"
    })
    int insert(Orgunit row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    @InsertProvider(type=OrgunitSqlProvider.class, method="insertSelective")
    int insertSelective(Orgunit row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    @SelectProvider(type=OrgunitSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="orgCode", property="orgcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="shortName", property="shortname", jdbcType=JdbcType.NVARCHAR),
        @Result(column="fullName", property="fullname", jdbcType=JdbcType.NVARCHAR),
        @Result(column="depNo", property="depno", jdbcType=JdbcType.VARCHAR),
        @Result(column="unitType", property="unittype", jdbcType=JdbcType.INTEGER),
        @Result(column="tel", property="tel", jdbcType=JdbcType.VARCHAR),
        @Result(column="fax", property="fax", jdbcType=JdbcType.VARCHAR),
        @Result(column="addr", property="addr", jdbcType=JdbcType.NVARCHAR),
        @Result(column="bossId", property="bossid", jdbcType=JdbcType.NUMERIC),
        @Result(column="onLine", property="online", jdbcType=JdbcType.TINYINT),
        @Result(column="sendEvent", property="sendevent", jdbcType=JdbcType.TINYINT),
        @Result(column="parentId", property="parentid", jdbcType=JdbcType.NUMERIC),
        @Result(column="section", property="section", jdbcType=JdbcType.VARCHAR),
        @Result(column="sequence", property="sequence", jdbcType=JdbcType.INTEGER),
        @Result(column="sentCaseId", property="sentcaseid", jdbcType=JdbcType.NUMERIC),
        @Result(column="t_APModifyDate", property="tApmodifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_APMotifier", property="tApmotifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_APMotifierIP", property="tApmotifierip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ReceiveDate", property="tReceivedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_ReceiveSystem", property="tReceivesystem", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreateDate", property="tCreatedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Creator", property="tCreator", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreatorIP", property="tCreatorip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifyDate", property="tModifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Modifier", property="tModifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifierIP", property="tModifierip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="refUnitCode", property="refunitcode", jdbcType=JdbcType.NVARCHAR),
        @Result(column="consumerUnitId", property="consumerunitid", jdbcType=JdbcType.NUMERIC)
    })
    List<Orgunit> selectByExample(OrgunitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    @Select({
        "select",
        "id, orgCode, shortName, fullName, depNo, unitType, tel, fax, addr, bossId, onLine, ",
        "sendEvent, parentId, section, sequence, sentCaseId, t_APModifyDate, t_APMotifier, ",
        "t_APMotifierIP, t_ReceiveDate, t_ReceiveSystem, t_CreateDate, t_Creator, t_CreatorIP, ",
        "t_ModifyDate, t_Modifier, t_ModifierIP, refUnitCode, consumerUnitId",
        "from OrgUnit",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="orgCode", property="orgcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="shortName", property="shortname", jdbcType=JdbcType.NVARCHAR),
        @Result(column="fullName", property="fullname", jdbcType=JdbcType.NVARCHAR),
        @Result(column="depNo", property="depno", jdbcType=JdbcType.VARCHAR),
        @Result(column="unitType", property="unittype", jdbcType=JdbcType.INTEGER),
        @Result(column="tel", property="tel", jdbcType=JdbcType.VARCHAR),
        @Result(column="fax", property="fax", jdbcType=JdbcType.VARCHAR),
        @Result(column="addr", property="addr", jdbcType=JdbcType.NVARCHAR),
        @Result(column="bossId", property="bossid", jdbcType=JdbcType.NUMERIC),
        @Result(column="onLine", property="online", jdbcType=JdbcType.TINYINT),
        @Result(column="sendEvent", property="sendevent", jdbcType=JdbcType.TINYINT),
        @Result(column="parentId", property="parentid", jdbcType=JdbcType.NUMERIC),
        @Result(column="section", property="section", jdbcType=JdbcType.VARCHAR),
        @Result(column="sequence", property="sequence", jdbcType=JdbcType.INTEGER),
        @Result(column="sentCaseId", property="sentcaseid", jdbcType=JdbcType.NUMERIC),
        @Result(column="t_APModifyDate", property="tApmodifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_APMotifier", property="tApmotifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_APMotifierIP", property="tApmotifierip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ReceiveDate", property="tReceivedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_ReceiveSystem", property="tReceivesystem", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreateDate", property="tCreatedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Creator", property="tCreator", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreatorIP", property="tCreatorip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifyDate", property="tModifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Modifier", property="tModifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifierIP", property="tModifierip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="refUnitCode", property="refunitcode", jdbcType=JdbcType.NVARCHAR),
        @Result(column="consumerUnitId", property="consumerunitid", jdbcType=JdbcType.NUMERIC)
    })
    Orgunit selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    @UpdateProvider(type=OrgunitSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") Orgunit row, @Param("example") OrgunitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    @UpdateProvider(type=OrgunitSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") Orgunit row, @Param("example") OrgunitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    @UpdateProvider(type=OrgunitSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Orgunit row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrgUnit
     *
     * @mbg.generated Mon Sep 01 12:09:45 CST 2025
     */
    @Update({
        "update OrgUnit",
        "set orgCode = #{orgcode,jdbcType=VARCHAR},",
          "shortName = #{shortname,jdbcType=NVARCHAR},",
          "fullName = #{fullname,jdbcType=NVARCHAR},",
          "depNo = #{depno,jdbcType=VARCHAR},",
          "unitType = #{unittype,jdbcType=INTEGER},",
          "tel = #{tel,jdbcType=VARCHAR},",
          "fax = #{fax,jdbcType=VARCHAR},",
          "addr = #{addr,jdbcType=NVARCHAR},",
          "bossId = #{bossid,jdbcType=NUMERIC},",
          "onLine = #{online,jdbcType=TINYINT},",
          "sendEvent = #{sendevent,jdbcType=TINYINT},",
          "parentId = #{parentid,jdbcType=NUMERIC},",
          "section = #{section,jdbcType=VARCHAR},",
          "sequence = #{sequence,jdbcType=INTEGER},",
          "sentCaseId = #{sentcaseid,jdbcType=NUMERIC},",
          "t_APModifyDate = #{tApmodifydate,jdbcType=TIMESTAMP},",
          "t_APMotifier = #{tApmotifier,jdbcType=NVARCHAR},",
          "t_APMotifierIP = #{tApmotifierip,jdbcType=NVARCHAR},",
          "t_ReceiveDate = #{tReceivedate,jdbcType=TIMESTAMP},",
          "t_ReceiveSystem = #{tReceivesystem,jdbcType=NVARCHAR},",
          "t_CreateDate = #{tCreatedate,jdbcType=TIMESTAMP},",
          "t_Creator = #{tCreator,jdbcType=NVARCHAR},",
          "t_CreatorIP = #{tCreatorip,jdbcType=NVARCHAR},",
          "t_ModifyDate = #{tModifydate,jdbcType=TIMESTAMP},",
          "t_Modifier = #{tModifier,jdbcType=NVARCHAR},",
          "t_ModifierIP = #{tModifierip,jdbcType=NVARCHAR},",
          "refUnitCode = #{refunitcode,jdbcType=NVARCHAR},",
          "consumerUnitId = #{consumerunitid,jdbcType=NUMERIC}",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(Orgunit row);
    
    @Select(" SELECT o.* FROM OrgUnit o JOIN Belong b ON b.orgUnitId = o.id JOIN Personnel p ON p.id = b.personnelId " +
			" WHERE p.idNum = #{idNum} ")
	List<Orgunit> findOrgunitByPersonnelIdNum(String idNum);
    
    @Select(" SELECT o.*, b.subOrgUnitId FROM OrgUnit o JOIN Belong b ON b.orgUnitId = o.id JOIN Personnel p ON p.id = b.personnelId " +
			" WHERE p.idNum = #{idNum} ")
    List<OrgunitWithBelong> findOrgunitWithBelongByPersonnelIdNum(String idNum);
	
	@Select("SELECT b.* FROM Belong a " +
			"INNER JOIN OrgUnit b ON a.orgUnitId = b.id " +
			"WHERE a.personnelId = #{personnelId}")
	List<Orgunit> findOrgunitsByPersonnelId(BigDecimal personnelId);

	@Select("SELECT b.* FROM Belong a " +
			"INNER JOIN OrgUnit b ON a.orgUnitId = b.id " +
			"WHERE a.suborgunitid = #{suborgunitid}")
	List<Orgunit> findOrgunitBySuborgunitid(BigDecimal suborgunitid);
}