package com.kd.ci.infrastructure.persistence.mapper.first;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.jdbc.SQL;

import com.kd.ci.domain.first.Personnel;
import com.kd.ci.domain.first.PersonnelExample;
import com.kd.ci.domain.first.PersonnelExample.Criteria;
import com.kd.ci.domain.first.PersonnelExample.Criterion;

public class PersonnelSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String countByExample(PersonnelExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("Personnel");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String deleteByExample(PersonnelExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("Personnel");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String insertSelective(Personnel row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("Personnel");
        
        if (row.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=NUMERIC}");
        }
        
        if (row.getCode() != null) {
            sql.VALUES("code", "#{code,jdbcType=VARCHAR}");
        }
        
        if (row.getIdnum() != null) {
            sql.VALUES("idNum", "#{idnum,jdbcType=VARCHAR}");
        }
        
        if (row.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=NVARCHAR}");
        }
        
        if (row.getTel() != null) {
            sql.VALUES("tel", "#{tel,jdbcType=VARCHAR}");
        }
        
        if (row.getTel2() != null) {
            sql.VALUES("tel2", "#{tel2,jdbcType=VARCHAR}");
        }
        
        if (row.getTitlecode() != null) {
            sql.VALUES("titleCode", "#{titlecode,jdbcType=VARCHAR}");
        }
        
        if (row.getTitlename() != null) {
            sql.VALUES("titleName", "#{titlename,jdbcType=NVARCHAR}");
        }
        
        if (row.getEmail1() != null) {
            sql.VALUES("email1", "#{email1,jdbcType=VARCHAR}");
        }
        
        if (row.getEmail2() != null) {
            sql.VALUES("email2", "#{email2,jdbcType=VARCHAR}");
        }
        
        if (row.getEmail3() != null) {
            sql.VALUES("email3", "#{email3,jdbcType=VARCHAR}");
        }
        
        if (row.getPassword() != null) {
            sql.VALUES("password", "#{password,jdbcType=VARCHAR}");
        }
        
        if (row.getEnabled() != null) {
            sql.VALUES("enabled", "#{enabled,jdbcType=TINYINT}");
        }
        
        if (row.getEaccount() != null) {
            sql.VALUES("eaccount", "#{eaccount,jdbcType=VARCHAR}");
        }
        
        if (row.getMobile() != null) {
            sql.VALUES("mobile", "#{mobile,jdbcType=VARCHAR}");
        }
        
        if (row.getStartdate() != null) {
            sql.VALUES("startDate", "#{startdate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getEnddate() != null) {
            sql.VALUES("endDate", "#{enddate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getLoginip() != null) {
            sql.VALUES("loginIP", "#{loginip,jdbcType=VARCHAR}");
        }
        
        if (row.getSsokey() != null) {
            sql.VALUES("ssoKey", "#{ssokey,jdbcType=VARCHAR}");
        }
        
        if (row.getInformemail1() != null) {
            sql.VALUES("informEmail1", "#{informemail1,jdbcType=VARCHAR}");
        }
        
        if (row.getInformemail2() != null) {
            sql.VALUES("informEmail2", "#{informemail2,jdbcType=VARCHAR}");
        }
        
        if (row.getInformmobile() != null) {
            sql.VALUES("informMobile", "#{informmobile,jdbcType=VARCHAR}");
        }
        
        if (row.getBkidnum() != null) {
            sql.VALUES("bkIdNum", "#{bkidnum,jdbcType=VARCHAR}");
        }
        
        if (row.getPid() != null) {
            sql.VALUES("pid", "#{pid,jdbcType=VARCHAR}");
        }
        
        if (row.getGroupnum() != null) {
            sql.VALUES("groupNum", "#{groupnum,jdbcType=INTEGER}");
        }
        
        if (row.getIschangpwd() != null) {
            sql.VALUES("isChangPwd", "#{ischangpwd,jdbcType=VARCHAR}");
        }
        
        if (row.gettCreatedate() != null) {
            sql.VALUES("T_CREATEDATE", "#{tCreatedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getIsnew() != null) {
            sql.VALUES("isNew", "#{isnew,jdbcType=VARCHAR}");
        }
        
        if (row.gettApmodifydate() != null) {
            sql.VALUES("t_APModifyDate", "#{tApmodifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettApmotifier() != null) {
            sql.VALUES("t_APMotifier", "#{tApmotifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettApmotifierip() != null) {
            sql.VALUES("t_APMotifierIP", "#{tApmotifierip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettReceivedate() != null) {
            sql.VALUES("t_ReceiveDate", "#{tReceivedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettReceivesystem() != null) {
            sql.VALUES("t_ReceiveSystem", "#{tReceivesystem,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreator() != null) {
            sql.VALUES("t_Creator", "#{tCreator,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreatorip() != null) {
            sql.VALUES("t_CreatorIP", "#{tCreatorip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifydate() != null) {
            sql.VALUES("t_ModifyDate", "#{tModifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettModifier() != null) {
            sql.VALUES("t_Modifier", "#{tModifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifierip() != null) {
            sql.VALUES("t_ModifierIP", "#{tModifierip,jdbcType=NVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String selectByExample(PersonnelExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("code");
        sql.SELECT("idNum");
        sql.SELECT("name");
        sql.SELECT("tel");
        sql.SELECT("tel2");
        sql.SELECT("titleCode");
        sql.SELECT("titleName");
        sql.SELECT("email1");
        sql.SELECT("email2");
        sql.SELECT("email3");
        sql.SELECT("password");
        sql.SELECT("enabled");
        sql.SELECT("eaccount");
        sql.SELECT("mobile");
        sql.SELECT("startDate");
        sql.SELECT("endDate");
        sql.SELECT("loginIP");
        sql.SELECT("ssoKey");
        sql.SELECT("informEmail1");
        sql.SELECT("informEmail2");
        sql.SELECT("informMobile");
        sql.SELECT("bkIdNum");
        sql.SELECT("pid");
        sql.SELECT("groupNum");
        sql.SELECT("isChangPwd");
        sql.SELECT("T_CREATEDATE");
        sql.SELECT("isNew");
        sql.SELECT("t_APModifyDate");
        sql.SELECT("t_APMotifier");
        sql.SELECT("t_APMotifierIP");
        sql.SELECT("t_ReceiveDate");
        sql.SELECT("t_ReceiveSystem");
        sql.SELECT("t_Creator");
        sql.SELECT("t_CreatorIP");
        sql.SELECT("t_ModifyDate");
        sql.SELECT("t_Modifier");
        sql.SELECT("t_ModifierIP");
        sql.FROM("Personnel");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Personnel row = (Personnel) parameter.get("row");
        PersonnelExample example = (PersonnelExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("Personnel");
        
        if (row.getId() != null) {
            sql.SET("id = #{row.id,jdbcType=NUMERIC}");
        }
        
        if (row.getCode() != null) {
            sql.SET("code = #{row.code,jdbcType=VARCHAR}");
        }
        
        if (row.getIdnum() != null) {
            sql.SET("idNum = #{row.idnum,jdbcType=VARCHAR}");
        }
        
        if (row.getName() != null) {
            sql.SET("name = #{row.name,jdbcType=NVARCHAR}");
        }
        
        if (row.getTel() != null) {
            sql.SET("tel = #{row.tel,jdbcType=VARCHAR}");
        }
        
        if (row.getTel2() != null) {
            sql.SET("tel2 = #{row.tel2,jdbcType=VARCHAR}");
        }
        
        if (row.getTitlecode() != null) {
            sql.SET("titleCode = #{row.titlecode,jdbcType=VARCHAR}");
        }
        
        if (row.getTitlename() != null) {
            sql.SET("titleName = #{row.titlename,jdbcType=NVARCHAR}");
        }
        
        if (row.getEmail1() != null) {
            sql.SET("email1 = #{row.email1,jdbcType=VARCHAR}");
        }
        
        if (row.getEmail2() != null) {
            sql.SET("email2 = #{row.email2,jdbcType=VARCHAR}");
        }
        
        if (row.getEmail3() != null) {
            sql.SET("email3 = #{row.email3,jdbcType=VARCHAR}");
        }
        
        if (row.getPassword() != null) {
            sql.SET("password = #{row.password,jdbcType=VARCHAR}");
        }
        
        if (row.getEnabled() != null) {
            sql.SET("enabled = #{row.enabled,jdbcType=TINYINT}");
        }
        
        if (row.getEaccount() != null) {
            sql.SET("eaccount = #{row.eaccount,jdbcType=VARCHAR}");
        }
        
        if (row.getMobile() != null) {
            sql.SET("mobile = #{row.mobile,jdbcType=VARCHAR}");
        }
        
        if (row.getStartdate() != null) {
            sql.SET("startDate = #{row.startdate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getEnddate() != null) {
            sql.SET("endDate = #{row.enddate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getLoginip() != null) {
            sql.SET("loginIP = #{row.loginip,jdbcType=VARCHAR}");
        }
        
        if (row.getSsokey() != null) {
            sql.SET("ssoKey = #{row.ssokey,jdbcType=VARCHAR}");
        }
        
        if (row.getInformemail1() != null) {
            sql.SET("informEmail1 = #{row.informemail1,jdbcType=VARCHAR}");
        }
        
        if (row.getInformemail2() != null) {
            sql.SET("informEmail2 = #{row.informemail2,jdbcType=VARCHAR}");
        }
        
        if (row.getInformmobile() != null) {
            sql.SET("informMobile = #{row.informmobile,jdbcType=VARCHAR}");
        }
        
        if (row.getBkidnum() != null) {
            sql.SET("bkIdNum = #{row.bkidnum,jdbcType=VARCHAR}");
        }
        
        if (row.getPid() != null) {
            sql.SET("pid = #{row.pid,jdbcType=VARCHAR}");
        }
        
        if (row.getGroupnum() != null) {
            sql.SET("groupNum = #{row.groupnum,jdbcType=INTEGER}");
        }
        
        if (row.getIschangpwd() != null) {
            sql.SET("isChangPwd = #{row.ischangpwd,jdbcType=VARCHAR}");
        }
        
        if (row.gettCreatedate() != null) {
            sql.SET("T_CREATEDATE = #{row.tCreatedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getIsnew() != null) {
            sql.SET("isNew = #{row.isnew,jdbcType=VARCHAR}");
        }
        
        if (row.gettApmodifydate() != null) {
            sql.SET("t_APModifyDate = #{row.tApmodifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettApmotifier() != null) {
            sql.SET("t_APMotifier = #{row.tApmotifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettApmotifierip() != null) {
            sql.SET("t_APMotifierIP = #{row.tApmotifierip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettReceivedate() != null) {
            sql.SET("t_ReceiveDate = #{row.tReceivedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettReceivesystem() != null) {
            sql.SET("t_ReceiveSystem = #{row.tReceivesystem,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreator() != null) {
            sql.SET("t_Creator = #{row.tCreator,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreatorip() != null) {
            sql.SET("t_CreatorIP = #{row.tCreatorip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifydate() != null) {
            sql.SET("t_ModifyDate = #{row.tModifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettModifier() != null) {
            sql.SET("t_Modifier = #{row.tModifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifierip() != null) {
            sql.SET("t_ModifierIP = #{row.tModifierip,jdbcType=NVARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("Personnel");
        
        sql.SET("id = #{row.id,jdbcType=NUMERIC}");
        sql.SET("code = #{row.code,jdbcType=VARCHAR}");
        sql.SET("idNum = #{row.idnum,jdbcType=VARCHAR}");
        sql.SET("name = #{row.name,jdbcType=NVARCHAR}");
        sql.SET("tel = #{row.tel,jdbcType=VARCHAR}");
        sql.SET("tel2 = #{row.tel2,jdbcType=VARCHAR}");
        sql.SET("titleCode = #{row.titlecode,jdbcType=VARCHAR}");
        sql.SET("titleName = #{row.titlename,jdbcType=NVARCHAR}");
        sql.SET("email1 = #{row.email1,jdbcType=VARCHAR}");
        sql.SET("email2 = #{row.email2,jdbcType=VARCHAR}");
        sql.SET("email3 = #{row.email3,jdbcType=VARCHAR}");
        sql.SET("password = #{row.password,jdbcType=VARCHAR}");
        sql.SET("enabled = #{row.enabled,jdbcType=TINYINT}");
        sql.SET("eaccount = #{row.eaccount,jdbcType=VARCHAR}");
        sql.SET("mobile = #{row.mobile,jdbcType=VARCHAR}");
        sql.SET("startDate = #{row.startdate,jdbcType=TIMESTAMP}");
        sql.SET("endDate = #{row.enddate,jdbcType=TIMESTAMP}");
        sql.SET("loginIP = #{row.loginip,jdbcType=VARCHAR}");
        sql.SET("ssoKey = #{row.ssokey,jdbcType=VARCHAR}");
        sql.SET("informEmail1 = #{row.informemail1,jdbcType=VARCHAR}");
        sql.SET("informEmail2 = #{row.informemail2,jdbcType=VARCHAR}");
        sql.SET("informMobile = #{row.informmobile,jdbcType=VARCHAR}");
        sql.SET("bkIdNum = #{row.bkidnum,jdbcType=VARCHAR}");
        sql.SET("pid = #{row.pid,jdbcType=VARCHAR}");
        sql.SET("groupNum = #{row.groupnum,jdbcType=INTEGER}");
        sql.SET("isChangPwd = #{row.ischangpwd,jdbcType=VARCHAR}");
        sql.SET("T_CREATEDATE = #{row.tCreatedate,jdbcType=TIMESTAMP}");
        sql.SET("isNew = #{row.isnew,jdbcType=VARCHAR}");
        sql.SET("t_APModifyDate = #{row.tApmodifydate,jdbcType=TIMESTAMP}");
        sql.SET("t_APMotifier = #{row.tApmotifier,jdbcType=NVARCHAR}");
        sql.SET("t_APMotifierIP = #{row.tApmotifierip,jdbcType=NVARCHAR}");
        sql.SET("t_ReceiveDate = #{row.tReceivedate,jdbcType=TIMESTAMP}");
        sql.SET("t_ReceiveSystem = #{row.tReceivesystem,jdbcType=NVARCHAR}");
        sql.SET("t_Creator = #{row.tCreator,jdbcType=NVARCHAR}");
        sql.SET("t_CreatorIP = #{row.tCreatorip,jdbcType=NVARCHAR}");
        sql.SET("t_ModifyDate = #{row.tModifydate,jdbcType=TIMESTAMP}");
        sql.SET("t_Modifier = #{row.tModifier,jdbcType=NVARCHAR}");
        sql.SET("t_ModifierIP = #{row.tModifierip,jdbcType=NVARCHAR}");
        
        PersonnelExample example = (PersonnelExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String updateByPrimaryKeySelective(Personnel row) {
        SQL sql = new SQL();
        sql.UPDATE("Personnel");
        
        if (row.getCode() != null) {
            sql.SET("code = #{code,jdbcType=VARCHAR}");
        }
        
        if (row.getIdnum() != null) {
            sql.SET("idNum = #{idnum,jdbcType=VARCHAR}");
        }
        
        if (row.getName() != null) {
            sql.SET("name = #{name,jdbcType=NVARCHAR}");
        }
        
        if (row.getTel() != null) {
            sql.SET("tel = #{tel,jdbcType=VARCHAR}");
        }
        
        if (row.getTel2() != null) {
            sql.SET("tel2 = #{tel2,jdbcType=VARCHAR}");
        }
        
        if (row.getTitlecode() != null) {
            sql.SET("titleCode = #{titlecode,jdbcType=VARCHAR}");
        }
        
        if (row.getTitlename() != null) {
            sql.SET("titleName = #{titlename,jdbcType=NVARCHAR}");
        }
        
        if (row.getEmail1() != null) {
            sql.SET("email1 = #{email1,jdbcType=VARCHAR}");
        }
        
        if (row.getEmail2() != null) {
            sql.SET("email2 = #{email2,jdbcType=VARCHAR}");
        }
        
        if (row.getEmail3() != null) {
            sql.SET("email3 = #{email3,jdbcType=VARCHAR}");
        }
        
        if (row.getPassword() != null) {
            sql.SET("password = #{password,jdbcType=VARCHAR}");
        }
        
        if (row.getEnabled() != null) {
            sql.SET("enabled = #{enabled,jdbcType=TINYINT}");
        }
        
        if (row.getEaccount() != null) {
            sql.SET("eaccount = #{eaccount,jdbcType=VARCHAR}");
        }
        
        if (row.getMobile() != null) {
            sql.SET("mobile = #{mobile,jdbcType=VARCHAR}");
        }
        
        if (row.getStartdate() != null) {
            sql.SET("startDate = #{startdate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getEnddate() != null) {
            sql.SET("endDate = #{enddate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getLoginip() != null) {
            sql.SET("loginIP = #{loginip,jdbcType=VARCHAR}");
        }
        
        if (row.getSsokey() != null) {
            sql.SET("ssoKey = #{ssokey,jdbcType=VARCHAR}");
        }
        
        if (row.getInformemail1() != null) {
            sql.SET("informEmail1 = #{informemail1,jdbcType=VARCHAR}");
        }
        
        if (row.getInformemail2() != null) {
            sql.SET("informEmail2 = #{informemail2,jdbcType=VARCHAR}");
        }
        
        if (row.getInformmobile() != null) {
            sql.SET("informMobile = #{informmobile,jdbcType=VARCHAR}");
        }
        
        if (row.getBkidnum() != null) {
            sql.SET("bkIdNum = #{bkidnum,jdbcType=VARCHAR}");
        }
        
        if (row.getPid() != null) {
            sql.SET("pid = #{pid,jdbcType=VARCHAR}");
        }
        
        if (row.getGroupnum() != null) {
            sql.SET("groupNum = #{groupnum,jdbcType=INTEGER}");
        }
        
        if (row.getIschangpwd() != null) {
            sql.SET("isChangPwd = #{ischangpwd,jdbcType=VARCHAR}");
        }
        
        if (row.gettCreatedate() != null) {
            sql.SET("T_CREATEDATE = #{tCreatedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getIsnew() != null) {
            sql.SET("isNew = #{isnew,jdbcType=VARCHAR}");
        }
        
        if (row.gettApmodifydate() != null) {
            sql.SET("t_APModifyDate = #{tApmodifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettApmotifier() != null) {
            sql.SET("t_APMotifier = #{tApmotifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettApmotifierip() != null) {
            sql.SET("t_APMotifierIP = #{tApmotifierip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettReceivedate() != null) {
            sql.SET("t_ReceiveDate = #{tReceivedate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettReceivesystem() != null) {
            sql.SET("t_ReceiveSystem = #{tReceivesystem,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreator() != null) {
            sql.SET("t_Creator = #{tCreator,jdbcType=NVARCHAR}");
        }
        
        if (row.gettCreatorip() != null) {
            sql.SET("t_CreatorIP = #{tCreatorip,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifydate() != null) {
            sql.SET("t_ModifyDate = #{tModifydate,jdbcType=TIMESTAMP}");
        }
        
        if (row.gettModifier() != null) {
            sql.SET("t_Modifier = #{tModifier,jdbcType=NVARCHAR}");
        }
        
        if (row.gettModifierip() != null) {
            sql.SET("t_ModifierIP = #{tModifierip,jdbcType=NVARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=NUMERIC}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    protected void applyWhere(SQL sql, PersonnelExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
    
    public String selectPersonnelWithBelongForFSAP01(final Map<String, Object> params) {
        return new SQL() {{
            SELECT("p.id, p.name, bl.subOrgUnitId, p.idNum, p.titleName, p.enabled");
            FROM("Personnel p");
            INNER_JOIN("Belong bl ON p.id = bl.personnelid");

            if (params.get("qSelfOrgUnit") != null) {
                WHERE("bl.orgUnitId = #{qSelfOrgUnit}");
            }
            if (params.get("qSelfDeptId") != null) {
                WHERE("bl.subOrgUnitId = #{qSelfDeptId}");
            }
            if (params.get("qIdNum") != null && !((String) params.get("qIdNum")).isEmpty()) {
                WHERE("p.idNum LIKE CONCAT('%', #{qIdNum}, '%')");
            }
            if (params.get("qName") != null && !((String) params.get("qName")).isEmpty()) {
                WHERE("p.name LIKE CONCAT('%', #{qName}, '%')");
            }
            if (params.get("qStatus") != null) {
                WHERE("p.enabled = #{qStatus}");
            }
        }}.toString();
    }
}