package com.kd.ci.infrastructure.persistence.mapper.first;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.kd.ci.domain.first.Personnel;
import com.kd.ci.domain.first.PersonnelExample;

public interface PersonnelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    @SelectProvider(type=PersonnelSqlProvider.class, method="countByExample")
    long countByExample(PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    @DeleteProvider(type=PersonnelSqlProvider.class, method="deleteByExample")
    int deleteByExample(PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    @Delete({
        "delete from Personnel",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    @Insert({
        "insert into Personnel (id, code, ",
        "idNum, name, tel, ",
        "tel2, titleCode, ",
        "titleName, email1, ",
        "email2, email3, ",
        "password, enabled, ",
        "eaccount, mobile, ",
        "startDate, endDate, ",
        "loginIP, ssoKey, ",
        "informEmail1, informEmail2, ",
        "informMobile, bkIdNum, ",
        "pid, groupNum, isChangPwd, ",
        "T_CREATEDATE, isNew, ",
        "t_APModifyDate, t_APMotifier, ",
        "t_APMotifierIP, t_ReceiveDate, ",
        "t_ReceiveSystem, t_Creator, ",
        "t_CreatorIP, t_ModifyDate, ",
        "t_Modifier, t_ModifierIP)",
        "values (#{id,jdbcType=NUMERIC}, #{code,jdbcType=VARCHAR}, ",
        "#{idnum,jdbcType=VARCHAR}, #{name,jdbcType=NVARCHAR}, #{tel,jdbcType=VARCHAR}, ",
        "#{tel2,jdbcType=VARCHAR}, #{titlecode,jdbcType=VARCHAR}, ",
        "#{titlename,jdbcType=NVARCHAR}, #{email1,jdbcType=VARCHAR}, ",
        "#{email2,jdbcType=VARCHAR}, #{email3,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{enabled,jdbcType=TINYINT}, ",
        "#{eaccount,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR}, ",
        "#{startdate,jdbcType=TIMESTAMP}, #{enddate,jdbcType=TIMESTAMP}, ",
        "#{loginip,jdbcType=VARCHAR}, #{ssokey,jdbcType=VARCHAR}, ",
        "#{informemail1,jdbcType=VARCHAR}, #{informemail2,jdbcType=VARCHAR}, ",
        "#{informmobile,jdbcType=VARCHAR}, #{bkidnum,jdbcType=VARCHAR}, ",
        "#{pid,jdbcType=VARCHAR}, #{groupnum,jdbcType=INTEGER}, #{ischangpwd,jdbcType=VARCHAR}, ",
        "#{tCreatedate,jdbcType=TIMESTAMP}, #{isnew,jdbcType=VARCHAR}, ",
        "#{tApmodifydate,jdbcType=TIMESTAMP}, #{tApmotifier,jdbcType=NVARCHAR}, ",
        "#{tApmotifierip,jdbcType=NVARCHAR}, #{tReceivedate,jdbcType=TIMESTAMP}, ",
        "#{tReceivesystem,jdbcType=NVARCHAR}, #{tCreator,jdbcType=NVARCHAR}, ",
        "#{tCreatorip,jdbcType=NVARCHAR}, #{tModifydate,jdbcType=TIMESTAMP}, ",
        "#{tModifier,jdbcType=NVARCHAR}, #{tModifierip,jdbcType=NVARCHAR})"
    })
    int insert(Personnel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    @InsertProvider(type=PersonnelSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys = true, keyProperty = "id")
    int insertSelective(Personnel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    @SelectProvider(type=PersonnelSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="idNum", property="idnum", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.NVARCHAR),
        @Result(column="tel", property="tel", jdbcType=JdbcType.VARCHAR),
        @Result(column="tel2", property="tel2", jdbcType=JdbcType.VARCHAR),
        @Result(column="titleCode", property="titlecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="titleName", property="titlename", jdbcType=JdbcType.NVARCHAR),
        @Result(column="email1", property="email1", jdbcType=JdbcType.VARCHAR),
        @Result(column="email2", property="email2", jdbcType=JdbcType.VARCHAR),
        @Result(column="email3", property="email3", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="enabled", property="enabled", jdbcType=JdbcType.TINYINT),
        @Result(column="eaccount", property="eaccount", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="startDate", property="startdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="endDate", property="enddate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="loginIP", property="loginip", jdbcType=JdbcType.VARCHAR),
        @Result(column="ssoKey", property="ssokey", jdbcType=JdbcType.VARCHAR),
        @Result(column="informEmail1", property="informemail1", jdbcType=JdbcType.VARCHAR),
        @Result(column="informEmail2", property="informemail2", jdbcType=JdbcType.VARCHAR),
        @Result(column="informMobile", property="informmobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="bkIdNum", property="bkidnum", jdbcType=JdbcType.VARCHAR),
        @Result(column="pid", property="pid", jdbcType=JdbcType.VARCHAR),
        @Result(column="groupNum", property="groupnum", jdbcType=JdbcType.INTEGER),
        @Result(column="isChangPwd", property="ischangpwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="T_CREATEDATE", property="tCreatedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="isNew", property="isnew", jdbcType=JdbcType.VARCHAR),
        @Result(column="t_APModifyDate", property="tApmodifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_APMotifier", property="tApmotifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_APMotifierIP", property="tApmotifierip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ReceiveDate", property="tReceivedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_ReceiveSystem", property="tReceivesystem", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_Creator", property="tCreator", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreatorIP", property="tCreatorip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifyDate", property="tModifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Modifier", property="tModifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifierIP", property="tModifierip", jdbcType=JdbcType.NVARCHAR)
    })
    List<Personnel> selectByExample(PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    @Select({
        "select",
        "id, code, idNum, name, tel, tel2, titleCode, titleName, email1, email2, email3, ",
        "password, enabled, eaccount, mobile, startDate, endDate, loginIP, ssoKey, informEmail1, ",
        "informEmail2, informMobile, bkIdNum, pid, groupNum, isChangPwd, T_CREATEDATE, ",
        "isNew, t_APModifyDate, t_APMotifier, t_APMotifierIP, t_ReceiveDate, t_ReceiveSystem, ",
        "t_Creator, t_CreatorIP, t_ModifyDate, t_Modifier, t_ModifierIP",
        "from Personnel",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="idNum", property="idnum", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.NVARCHAR),
        @Result(column="tel", property="tel", jdbcType=JdbcType.VARCHAR),
        @Result(column="tel2", property="tel2", jdbcType=JdbcType.VARCHAR),
        @Result(column="titleCode", property="titlecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="titleName", property="titlename", jdbcType=JdbcType.NVARCHAR),
        @Result(column="email1", property="email1", jdbcType=JdbcType.VARCHAR),
        @Result(column="email2", property="email2", jdbcType=JdbcType.VARCHAR),
        @Result(column="email3", property="email3", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="enabled", property="enabled", jdbcType=JdbcType.TINYINT),
        @Result(column="eaccount", property="eaccount", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="startDate", property="startdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="endDate", property="enddate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="loginIP", property="loginip", jdbcType=JdbcType.VARCHAR),
        @Result(column="ssoKey", property="ssokey", jdbcType=JdbcType.VARCHAR),
        @Result(column="informEmail1", property="informemail1", jdbcType=JdbcType.VARCHAR),
        @Result(column="informEmail2", property="informemail2", jdbcType=JdbcType.VARCHAR),
        @Result(column="informMobile", property="informmobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="bkIdNum", property="bkidnum", jdbcType=JdbcType.VARCHAR),
        @Result(column="pid", property="pid", jdbcType=JdbcType.VARCHAR),
        @Result(column="groupNum", property="groupnum", jdbcType=JdbcType.INTEGER),
        @Result(column="isChangPwd", property="ischangpwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="T_CREATEDATE", property="tCreatedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="isNew", property="isnew", jdbcType=JdbcType.VARCHAR),
        @Result(column="t_APModifyDate", property="tApmodifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_APMotifier", property="tApmotifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_APMotifierIP", property="tApmotifierip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ReceiveDate", property="tReceivedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_ReceiveSystem", property="tReceivesystem", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_Creator", property="tCreator", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_CreatorIP", property="tCreatorip", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifyDate", property="tModifydate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="t_Modifier", property="tModifier", jdbcType=JdbcType.NVARCHAR),
        @Result(column="t_ModifierIP", property="tModifierip", jdbcType=JdbcType.NVARCHAR)
    })
    Personnel selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    @UpdateProvider(type=PersonnelSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") Personnel row, @Param("example") PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    @UpdateProvider(type=PersonnelSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") Personnel row, @Param("example") PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    @UpdateProvider(type=PersonnelSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Personnel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    @Update({
        "update Personnel",
        "set code = #{code,jdbcType=VARCHAR},",
          "idNum = #{idnum,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=NVARCHAR},",
          "tel = #{tel,jdbcType=VARCHAR},",
          "tel2 = #{tel2,jdbcType=VARCHAR},",
          "titleCode = #{titlecode,jdbcType=VARCHAR},",
          "titleName = #{titlename,jdbcType=NVARCHAR},",
          "email1 = #{email1,jdbcType=VARCHAR},",
          "email2 = #{email2,jdbcType=VARCHAR},",
          "email3 = #{email3,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "enabled = #{enabled,jdbcType=TINYINT},",
          "eaccount = #{eaccount,jdbcType=VARCHAR},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "startDate = #{startdate,jdbcType=TIMESTAMP},",
          "endDate = #{enddate,jdbcType=TIMESTAMP},",
          "loginIP = #{loginip,jdbcType=VARCHAR},",
          "ssoKey = #{ssokey,jdbcType=VARCHAR},",
          "informEmail1 = #{informemail1,jdbcType=VARCHAR},",
          "informEmail2 = #{informemail2,jdbcType=VARCHAR},",
          "informMobile = #{informmobile,jdbcType=VARCHAR},",
          "bkIdNum = #{bkidnum,jdbcType=VARCHAR},",
          "pid = #{pid,jdbcType=VARCHAR},",
          "groupNum = #{groupnum,jdbcType=INTEGER},",
          "isChangPwd = #{ischangpwd,jdbcType=VARCHAR},",
          "T_CREATEDATE = #{tCreatedate,jdbcType=TIMESTAMP},",
          "isNew = #{isnew,jdbcType=VARCHAR},",
          "t_APModifyDate = #{tApmodifydate,jdbcType=TIMESTAMP},",
          "t_APMotifier = #{tApmotifier,jdbcType=NVARCHAR},",
          "t_APMotifierIP = #{tApmotifierip,jdbcType=NVARCHAR},",
          "t_ReceiveDate = #{tReceivedate,jdbcType=TIMESTAMP},",
          "t_ReceiveSystem = #{tReceivesystem,jdbcType=NVARCHAR},",
          "t_Creator = #{tCreator,jdbcType=NVARCHAR},",
          "t_CreatorIP = #{tCreatorip,jdbcType=NVARCHAR},",
          "t_ModifyDate = #{tModifydate,jdbcType=TIMESTAMP},",
          "t_Modifier = #{tModifier,jdbcType=NVARCHAR},",
          "t_ModifierIP = #{tModifierip,jdbcType=NVARCHAR}",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(Personnel row);
    
    @Select("SELECT a.acts_id " + 
			"FROM Personnel p " + 
			"JOIN Belong b ON b.personnelId = p.id " +
			"JOIN Belong_Act a ON a.Belong_id = b.id " +
			"WHERE p.idNum = #{idNum}")
	List<BigDecimal> findActsIdsByPersonnelIdNum(String idNum);
    
    @Select("SELECT * " +
    		"FROM Personnel " + 
    		"WHERE idNum = #{idNum}")
    Personnel findPersonnelByidNum(String idNum);
    
    @Select("SELECT * " +
    		"FROM Personnel " + 
    		"WHERE email1 = #{email} and enabled = 1")
    Personnel findPersonnelByEmail1(String email);
    
    @Select("SELECT p.* " +
    		"FROM Personnel p " + 
    		"JOIN AuditGroup ag on ag.personnelId = p.id " +
    		"WHERE ag.id = #{rid}")// and enabled = 1
    Personnel findPersonnelByAuditGroupId(BigDecimal rid);
    
	@Select("SELECT p.*, o.shortname, o.sequence " +
			"FROM Personnel p " +
			"JOIN Belong b ON p.id = b.personnelId " +
			"JOIN OrgUnit o ON b.suborgunitid = o.id " +
			"WHERE p.enabled = #{enabled} " +
			"ORDER BY o.sequence ASC ")
	List<Map<String, Object>> findPersonnelWithShortnameByEnabled(byte enabled); // 找 OrgUnit sequence 去排序

	@Select("SELECT p.email1 " +
			"FROM Personnel p " +
			"JOIN Belong b ON p.id = b.personnelId " +
			"JOIN OrgUnit o ON b.suborgunitid = o.id " +
			"WHERE o.id = #{SubOrgUnit} and p.enabled = 1")
	List<String> findPersonnelEmail1BySubOrgUnitId(String SubOrgUnit);
	
	@Select("SELECT p.email1 " +
			"FROM Personnel p " +
			"JOIN Belong b ON p.id = b.personnelId " +
			"JOIN Belong_act ba ON b.id = ba.Belong_id " +
			"JOIN act a ON ba.acts_id = a.id " +
			"WHERE a.id = #{actId} and p.enabled = 1")
	List<String> findPersonnelEmail1ByActId(String actId);
	
	
	@Select("SELECT userMail FROM FN_notLogin_List()")
	List<String> findInactiveUsermail();
	
	@Update("""
		<script>
		UPDATE Personnel
			SET enabled = #{enabled}
			WHERE id IN
				<foreach collection="ids" item="id" open="(" separator="," close=")">
					#{id}
				</foreach>
		</script>
		""")
	int batchEnabledByEnabledAndIds(@Param("enabled") byte enabled, @Param("ids") List<BigDecimal> ids);
	
	@Select("""
		SELECT p.id
		FROM Personnel p
		INNER JOIN Belong bl ON p.id = bl.personnelId
		INNER JOIN Belong_act ba ON ba.belong_id = bl.id
		INNER JOIN Act act ON act.id = ba.acts_Id
		WHERE act.chiName = #{chiName}
		AND p.enabled = 1
		""")
	List<BigDecimal> findPersonnelIdByActChiName(@Param("chiName") String chiName);
	
	@Select({
		"<script>",
		"SELECT TOP 1 o.shortname, p.name",
		"FROM personnel p",
		"LEFT JOIN Belong bl ON p.id = bl.personnelId",
		"LEFT JOIN orgunit o ON o.id = ",
		"    CASE",
		"        WHEN bl.subOrgUnitId IS NOT NULL THEN bl.subOrgUnitId",
		"        ELSE bl.orgUnitId",
		"    END",
		"WHERE p.idNum = #{idNum}",
		"</script>"
	})
	Map<String, Object> findOrgShortNameAndPersonnelNameByIdNum(@Param("idNum") String idNum);
	
	@Select({
		"<script>",
		"SELECT o.shortname, p.name, p.idNum",
		"FROM personnel p",
		"LEFT JOIN Belong bl ON p.id = bl.personnelId",
		"LEFT JOIN orgunit o ON o.id = ", 
		"    CASE",
		"        WHEN bl.subOrgUnitId IS NOT NULL THEN bl.subOrgUnitId", 
		"        ELSE bl.orgUnitId",
		"    END",
		"WHERE p.idNum IN ",
		"<foreach collection='idNums' item='idNum' open='(' separator=',' close=')'>",
		"#{idNum}",
		"</foreach>",
		"</script>"
	})
	List<Map<String, Object>> findOrgShortNameAndPersonnelNameByIdNumList(@Param("idNums") List<String> idNums);

	/** 檢核是否為管理者 */
	@Select("""
	        SELECT COUNT(*)
	        FROM personnel p
	        INNER JOIN belong bl ON p.id = bl.personnelId
	        INNER JOIN belong_act ba ON ba.Belong_id = bl.id
	        INNER JOIN act aa ON aa.id = ba.acts_id
	        WHERE aa.name = 'ADMIN'
	          AND p.enabled = '1'
	          AND p.id = #{id}
	        """)
	int countAdminById(@Param("id") BigDecimal id);
	
	@Select("""
	        SELECT COUNT(*) 
	        FROM personnel
	        WHERE enabled != '2'
	          AND idNum = #{email}
	    """)
	int countPersonnelByIdNumAndEnabledNotEquals2(@Param("email") String email);
	
	@Select("""
	        SELECT COUNT(*) 
	        FROM personnel
	        WHERE enabled = 0
	          AND idNum = #{email}
	    """)
	int countPersonnelByIdNumAndEnabledEquals0(@Param("email") String email);
	
	@Select("""
	        SELECT COUNT(*) 
	        FROM personnel
	        WHERE enabled = 1
	          AND idNum = #{email}
	    """)
	int countPersonnelByIdNumAndEnabledEquals1(@Param("email") String email);
	
	@Select({"<script>",
	    "SELECT email1 ",
	    "FROM Personnel p ",
	    "INNER JOIN belong bl ON p.id = bl.personnelid ",
	    "INNER JOIN belong_act ba ON ba.belong_id = bl.id ",
	    "INNER JOIN act a ON a.id = ba.acts_id ",
	    "WHERE a.name = 'ACCOUNT_AUDITOR' ",
	    "AND p.enabled = '1' ",
	    "AND bl.orgUnitid = #{orgUnitId}",
	    "</script>"})
	List<String> getAccountAuditorEmailsByOrgunit(@Param("orgUnitId") BigDecimal orgUnitId);
	
	@Select({"<script>",
	    "SELECT email1 ",
	    "FROM Personnel p ",
	    "INNER JOIN belong bl ON p.id = bl.personnelid ",
	    "INNER JOIN belong_act ba ON ba.belong_id = bl.id ",
	    "INNER JOIN act a ON a.id = ba.acts_id ",
	    "WHERE a.name = 'ACCOUNT_AUDITOR' ",
	    "AND p.enabled = '1' ",
	    "AND bl.subOrgUnitId = #{subOrgUnitId}",
	    "</script>"})
	List<String> getAccountAuditorEmailsBySuborgunit(@Param("subOrgUnitId") BigDecimal subOrgUnitId);
	
	/** 檢核使用者是否有權限 */
	@Select("""
			SELECT count(p.id)
			FROM Personnel p
			INNER JOIN Belong bl ON p.id = bl.personnelId
			INNER JOIN Belong_act ba ON ba.belong_id = bl.id
			INNER JOIN Act act ON act.id = ba.acts_Id
			WHERE act.name = #{name}
			AND p.enabled = 1 AND p.id = #{id}
			""")
	int countPersonnelIdByActName(@Param("name") String name, @Param("id") BigDecimal id);
	
	@Select("SELECT a.name " + 
			"FROM Personnel p " + 
			"JOIN Belong b ON b.personnelId = p.id " +
			"JOIN Belong_Act ba ON ba.Belong_id = b.id " +
			"JOIN act a ON a.id = ba.acts_id " + 
			"WHERE p.idNum = #{idNum}")
	List<String> findActNamesByPersonnelIdNum(String idNum);
	
}