package com.kd.ci.domain.first;

import java.math.BigDecimal;
import java.util.Date;

public class Act {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.id
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.chiName
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private String chiname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.actType
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private Integer acttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.name
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.level
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.t_APModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private Date tApmodifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.t_APMotifier
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private String tApmotifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.t_APMotifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private String tApmotifierip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.t_ReceiveDate
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private Date tReceivedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.t_ReceiveSystem
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private String tReceivesystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.t_CreateDate
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private Date tCreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.t_Creator
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private String tCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.t_CreatorIP
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private String tCreatorip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.t_ModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private Date tModifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.t_Modifier
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private String tModifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Act.t_ModifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    private String tModifierip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.id
     *
     * @return the value of Act.id
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.id
     *
     * @param id the value for Act.id
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.chiName
     *
     * @return the value of Act.chiName
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public String getChiname() {
        return chiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.chiName
     *
     * @param chiname the value for Act.chiName
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void setChiname(String chiname) {
        this.chiname = chiname == null ? null : chiname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.actType
     *
     * @return the value of Act.actType
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public Integer getActtype() {
        return acttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.actType
     *
     * @param acttype the value for Act.actType
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void setActtype(Integer acttype) {
        this.acttype = acttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.name
     *
     * @return the value of Act.name
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.name
     *
     * @param name the value for Act.name
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.level
     *
     * @return the value of Act.level
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.level
     *
     * @param level the value for Act.level
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.t_APModifyDate
     *
     * @return the value of Act.t_APModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public Date gettApmodifydate() {
        return tApmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.t_APModifyDate
     *
     * @param tApmodifydate the value for Act.t_APModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void settApmodifydate(Date tApmodifydate) {
        this.tApmodifydate = tApmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.t_APMotifier
     *
     * @return the value of Act.t_APMotifier
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public String gettApmotifier() {
        return tApmotifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.t_APMotifier
     *
     * @param tApmotifier the value for Act.t_APMotifier
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void settApmotifier(String tApmotifier) {
        this.tApmotifier = tApmotifier == null ? null : tApmotifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.t_APMotifierIP
     *
     * @return the value of Act.t_APMotifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public String gettApmotifierip() {
        return tApmotifierip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.t_APMotifierIP
     *
     * @param tApmotifierip the value for Act.t_APMotifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void settApmotifierip(String tApmotifierip) {
        this.tApmotifierip = tApmotifierip == null ? null : tApmotifierip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.t_ReceiveDate
     *
     * @return the value of Act.t_ReceiveDate
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public Date gettReceivedate() {
        return tReceivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.t_ReceiveDate
     *
     * @param tReceivedate the value for Act.t_ReceiveDate
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void settReceivedate(Date tReceivedate) {
        this.tReceivedate = tReceivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.t_ReceiveSystem
     *
     * @return the value of Act.t_ReceiveSystem
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public String gettReceivesystem() {
        return tReceivesystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.t_ReceiveSystem
     *
     * @param tReceivesystem the value for Act.t_ReceiveSystem
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void settReceivesystem(String tReceivesystem) {
        this.tReceivesystem = tReceivesystem == null ? null : tReceivesystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.t_CreateDate
     *
     * @return the value of Act.t_CreateDate
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public Date gettCreatedate() {
        return tCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.t_CreateDate
     *
     * @param tCreatedate the value for Act.t_CreateDate
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void settCreatedate(Date tCreatedate) {
        this.tCreatedate = tCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.t_Creator
     *
     * @return the value of Act.t_Creator
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public String gettCreator() {
        return tCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.t_Creator
     *
     * @param tCreator the value for Act.t_Creator
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void settCreator(String tCreator) {
        this.tCreator = tCreator == null ? null : tCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.t_CreatorIP
     *
     * @return the value of Act.t_CreatorIP
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public String gettCreatorip() {
        return tCreatorip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.t_CreatorIP
     *
     * @param tCreatorip the value for Act.t_CreatorIP
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void settCreatorip(String tCreatorip) {
        this.tCreatorip = tCreatorip == null ? null : tCreatorip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.t_ModifyDate
     *
     * @return the value of Act.t_ModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public Date gettModifydate() {
        return tModifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.t_ModifyDate
     *
     * @param tModifydate the value for Act.t_ModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void settModifydate(Date tModifydate) {
        this.tModifydate = tModifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.t_Modifier
     *
     * @return the value of Act.t_Modifier
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public String gettModifier() {
        return tModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.t_Modifier
     *
     * @param tModifier the value for Act.t_Modifier
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void settModifier(String tModifier) {
        this.tModifier = tModifier == null ? null : tModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Act.t_ModifierIP
     *
     * @return the value of Act.t_ModifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public String gettModifierip() {
        return tModifierip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Act.t_ModifierIP
     *
     * @param tModifierip the value for Act.t_ModifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void settModifierip(String tModifierip) {
        this.tModifierip = tModifierip == null ? null : tModifierip.trim();
    }
    
    public static Act of(BigDecimal id) {
        Act act = new Act();
        act.setId(id);
        return act;
    }
}