package com.kd.ci.domain.first;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public ActExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andChinameIsNull() {
            addCriterion("chiName is null");
            return (Criteria) this;
        }

        public Criteria andChinameIsNotNull() {
            addCriterion("chiName is not null");
            return (Criteria) this;
        }

        public Criteria andChinameEqualTo(String value) {
            addCriterion("chiName =", value, "chiname");
            return (Criteria) this;
        }

        public Criteria andChinameNotEqualTo(String value) {
            addCriterion("chiName <>", value, "chiname");
            return (Criteria) this;
        }

        public Criteria andChinameGreaterThan(String value) {
            addCriterion("chiName >", value, "chiname");
            return (Criteria) this;
        }

        public Criteria andChinameGreaterThanOrEqualTo(String value) {
            addCriterion("chiName >=", value, "chiname");
            return (Criteria) this;
        }

        public Criteria andChinameLessThan(String value) {
            addCriterion("chiName <", value, "chiname");
            return (Criteria) this;
        }

        public Criteria andChinameLessThanOrEqualTo(String value) {
            addCriterion("chiName <=", value, "chiname");
            return (Criteria) this;
        }

        public Criteria andChinameLike(String value) {
            addCriterion("chiName like", value, "chiname");
            return (Criteria) this;
        }

        public Criteria andChinameNotLike(String value) {
            addCriterion("chiName not like", value, "chiname");
            return (Criteria) this;
        }

        public Criteria andChinameIn(List<String> values) {
            addCriterion("chiName in", values, "chiname");
            return (Criteria) this;
        }

        public Criteria andChinameNotIn(List<String> values) {
            addCriterion("chiName not in", values, "chiname");
            return (Criteria) this;
        }

        public Criteria andChinameBetween(String value1, String value2) {
            addCriterion("chiName between", value1, value2, "chiname");
            return (Criteria) this;
        }

        public Criteria andChinameNotBetween(String value1, String value2) {
            addCriterion("chiName not between", value1, value2, "chiname");
            return (Criteria) this;
        }

        public Criteria andActtypeIsNull() {
            addCriterion("actType is null");
            return (Criteria) this;
        }

        public Criteria andActtypeIsNotNull() {
            addCriterion("actType is not null");
            return (Criteria) this;
        }

        public Criteria andActtypeEqualTo(Integer value) {
            addCriterion("actType =", value, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeNotEqualTo(Integer value) {
            addCriterion("actType <>", value, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeGreaterThan(Integer value) {
            addCriterion("actType >", value, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("actType >=", value, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeLessThan(Integer value) {
            addCriterion("actType <", value, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeLessThanOrEqualTo(Integer value) {
            addCriterion("actType <=", value, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeIn(List<Integer> values) {
            addCriterion("actType in", values, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeNotIn(List<Integer> values) {
            addCriterion("actType not in", values, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeBetween(Integer value1, Integer value2) {
            addCriterion("actType between", value1, value2, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeNotBetween(Integer value1, Integer value2) {
            addCriterion("actType not between", value1, value2, "acttype");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateIsNull() {
            addCriterion("t_APModifyDate is null");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateIsNotNull() {
            addCriterion("t_APModifyDate is not null");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateEqualTo(Date value) {
            addCriterion("t_APModifyDate =", value, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateNotEqualTo(Date value) {
            addCriterion("t_APModifyDate <>", value, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateGreaterThan(Date value) {
            addCriterion("t_APModifyDate >", value, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("t_APModifyDate >=", value, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateLessThan(Date value) {
            addCriterion("t_APModifyDate <", value, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateLessThanOrEqualTo(Date value) {
            addCriterion("t_APModifyDate <=", value, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateIn(List<Date> values) {
            addCriterion("t_APModifyDate in", values, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateNotIn(List<Date> values) {
            addCriterion("t_APModifyDate not in", values, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateBetween(Date value1, Date value2) {
            addCriterion("t_APModifyDate between", value1, value2, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateNotBetween(Date value1, Date value2) {
            addCriterion("t_APModifyDate not between", value1, value2, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmotifierIsNull() {
            addCriterion("t_APMotifier is null");
            return (Criteria) this;
        }

        public Criteria andTApmotifierIsNotNull() {
            addCriterion("t_APMotifier is not null");
            return (Criteria) this;
        }

        public Criteria andTApmotifierEqualTo(String value) {
            addCriterion("t_APMotifier =", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierNotEqualTo(String value) {
            addCriterion("t_APMotifier <>", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierGreaterThan(String value) {
            addCriterion("t_APMotifier >", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierGreaterThanOrEqualTo(String value) {
            addCriterion("t_APMotifier >=", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierLessThan(String value) {
            addCriterion("t_APMotifier <", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierLessThanOrEqualTo(String value) {
            addCriterion("t_APMotifier <=", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierLike(String value) {
            addCriterion("t_APMotifier like", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierNotLike(String value) {
            addCriterion("t_APMotifier not like", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierIn(List<String> values) {
            addCriterion("t_APMotifier in", values, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierNotIn(List<String> values) {
            addCriterion("t_APMotifier not in", values, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierBetween(String value1, String value2) {
            addCriterion("t_APMotifier between", value1, value2, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierNotBetween(String value1, String value2) {
            addCriterion("t_APMotifier not between", value1, value2, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripIsNull() {
            addCriterion("t_APMotifierIP is null");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripIsNotNull() {
            addCriterion("t_APMotifierIP is not null");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripEqualTo(String value) {
            addCriterion("t_APMotifierIP =", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripNotEqualTo(String value) {
            addCriterion("t_APMotifierIP <>", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripGreaterThan(String value) {
            addCriterion("t_APMotifierIP >", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripGreaterThanOrEqualTo(String value) {
            addCriterion("t_APMotifierIP >=", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripLessThan(String value) {
            addCriterion("t_APMotifierIP <", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripLessThanOrEqualTo(String value) {
            addCriterion("t_APMotifierIP <=", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripLike(String value) {
            addCriterion("t_APMotifierIP like", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripNotLike(String value) {
            addCriterion("t_APMotifierIP not like", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripIn(List<String> values) {
            addCriterion("t_APMotifierIP in", values, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripNotIn(List<String> values) {
            addCriterion("t_APMotifierIP not in", values, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripBetween(String value1, String value2) {
            addCriterion("t_APMotifierIP between", value1, value2, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripNotBetween(String value1, String value2) {
            addCriterion("t_APMotifierIP not between", value1, value2, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTReceivedateIsNull() {
            addCriterion("t_ReceiveDate is null");
            return (Criteria) this;
        }

        public Criteria andTReceivedateIsNotNull() {
            addCriterion("t_ReceiveDate is not null");
            return (Criteria) this;
        }

        public Criteria andTReceivedateEqualTo(Date value) {
            addCriterion("t_ReceiveDate =", value, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateNotEqualTo(Date value) {
            addCriterion("t_ReceiveDate <>", value, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateGreaterThan(Date value) {
            addCriterion("t_ReceiveDate >", value, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateGreaterThanOrEqualTo(Date value) {
            addCriterion("t_ReceiveDate >=", value, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateLessThan(Date value) {
            addCriterion("t_ReceiveDate <", value, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateLessThanOrEqualTo(Date value) {
            addCriterion("t_ReceiveDate <=", value, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateIn(List<Date> values) {
            addCriterion("t_ReceiveDate in", values, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateNotIn(List<Date> values) {
            addCriterion("t_ReceiveDate not in", values, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateBetween(Date value1, Date value2) {
            addCriterion("t_ReceiveDate between", value1, value2, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateNotBetween(Date value1, Date value2) {
            addCriterion("t_ReceiveDate not between", value1, value2, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemIsNull() {
            addCriterion("t_ReceiveSystem is null");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemIsNotNull() {
            addCriterion("t_ReceiveSystem is not null");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemEqualTo(String value) {
            addCriterion("t_ReceiveSystem =", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemNotEqualTo(String value) {
            addCriterion("t_ReceiveSystem <>", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemGreaterThan(String value) {
            addCriterion("t_ReceiveSystem >", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemGreaterThanOrEqualTo(String value) {
            addCriterion("t_ReceiveSystem >=", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemLessThan(String value) {
            addCriterion("t_ReceiveSystem <", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemLessThanOrEqualTo(String value) {
            addCriterion("t_ReceiveSystem <=", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemLike(String value) {
            addCriterion("t_ReceiveSystem like", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemNotLike(String value) {
            addCriterion("t_ReceiveSystem not like", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemIn(List<String> values) {
            addCriterion("t_ReceiveSystem in", values, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemNotIn(List<String> values) {
            addCriterion("t_ReceiveSystem not in", values, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemBetween(String value1, String value2) {
            addCriterion("t_ReceiveSystem between", value1, value2, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemNotBetween(String value1, String value2) {
            addCriterion("t_ReceiveSystem not between", value1, value2, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTCreatedateIsNull() {
            addCriterion("t_CreateDate is null");
            return (Criteria) this;
        }

        public Criteria andTCreatedateIsNotNull() {
            addCriterion("t_CreateDate is not null");
            return (Criteria) this;
        }

        public Criteria andTCreatedateEqualTo(Date value) {
            addCriterion("t_CreateDate =", value, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateNotEqualTo(Date value) {
            addCriterion("t_CreateDate <>", value, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateGreaterThan(Date value) {
            addCriterion("t_CreateDate >", value, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("t_CreateDate >=", value, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateLessThan(Date value) {
            addCriterion("t_CreateDate <", value, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("t_CreateDate <=", value, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateIn(List<Date> values) {
            addCriterion("t_CreateDate in", values, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateNotIn(List<Date> values) {
            addCriterion("t_CreateDate not in", values, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateBetween(Date value1, Date value2) {
            addCriterion("t_CreateDate between", value1, value2, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("t_CreateDate not between", value1, value2, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatorIsNull() {
            addCriterion("t_Creator is null");
            return (Criteria) this;
        }

        public Criteria andTCreatorIsNotNull() {
            addCriterion("t_Creator is not null");
            return (Criteria) this;
        }

        public Criteria andTCreatorEqualTo(String value) {
            addCriterion("t_Creator =", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorNotEqualTo(String value) {
            addCriterion("t_Creator <>", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorGreaterThan(String value) {
            addCriterion("t_Creator >", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("t_Creator >=", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorLessThan(String value) {
            addCriterion("t_Creator <", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorLessThanOrEqualTo(String value) {
            addCriterion("t_Creator <=", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorLike(String value) {
            addCriterion("t_Creator like", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorNotLike(String value) {
            addCriterion("t_Creator not like", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorIn(List<String> values) {
            addCriterion("t_Creator in", values, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorNotIn(List<String> values) {
            addCriterion("t_Creator not in", values, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorBetween(String value1, String value2) {
            addCriterion("t_Creator between", value1, value2, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorNotBetween(String value1, String value2) {
            addCriterion("t_Creator not between", value1, value2, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatoripIsNull() {
            addCriterion("t_CreatorIP is null");
            return (Criteria) this;
        }

        public Criteria andTCreatoripIsNotNull() {
            addCriterion("t_CreatorIP is not null");
            return (Criteria) this;
        }

        public Criteria andTCreatoripEqualTo(String value) {
            addCriterion("t_CreatorIP =", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripNotEqualTo(String value) {
            addCriterion("t_CreatorIP <>", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripGreaterThan(String value) {
            addCriterion("t_CreatorIP >", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripGreaterThanOrEqualTo(String value) {
            addCriterion("t_CreatorIP >=", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripLessThan(String value) {
            addCriterion("t_CreatorIP <", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripLessThanOrEqualTo(String value) {
            addCriterion("t_CreatorIP <=", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripLike(String value) {
            addCriterion("t_CreatorIP like", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripNotLike(String value) {
            addCriterion("t_CreatorIP not like", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripIn(List<String> values) {
            addCriterion("t_CreatorIP in", values, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripNotIn(List<String> values) {
            addCriterion("t_CreatorIP not in", values, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripBetween(String value1, String value2) {
            addCriterion("t_CreatorIP between", value1, value2, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripNotBetween(String value1, String value2) {
            addCriterion("t_CreatorIP not between", value1, value2, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTModifydateIsNull() {
            addCriterion("t_ModifyDate is null");
            return (Criteria) this;
        }

        public Criteria andTModifydateIsNotNull() {
            addCriterion("t_ModifyDate is not null");
            return (Criteria) this;
        }

        public Criteria andTModifydateEqualTo(Date value) {
            addCriterion("t_ModifyDate =", value, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateNotEqualTo(Date value) {
            addCriterion("t_ModifyDate <>", value, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateGreaterThan(Date value) {
            addCriterion("t_ModifyDate >", value, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("t_ModifyDate >=", value, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateLessThan(Date value) {
            addCriterion("t_ModifyDate <", value, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateLessThanOrEqualTo(Date value) {
            addCriterion("t_ModifyDate <=", value, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateIn(List<Date> values) {
            addCriterion("t_ModifyDate in", values, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateNotIn(List<Date> values) {
            addCriterion("t_ModifyDate not in", values, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateBetween(Date value1, Date value2) {
            addCriterion("t_ModifyDate between", value1, value2, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateNotBetween(Date value1, Date value2) {
            addCriterion("t_ModifyDate not between", value1, value2, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifierIsNull() {
            addCriterion("t_Modifier is null");
            return (Criteria) this;
        }

        public Criteria andTModifierIsNotNull() {
            addCriterion("t_Modifier is not null");
            return (Criteria) this;
        }

        public Criteria andTModifierEqualTo(String value) {
            addCriterion("t_Modifier =", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierNotEqualTo(String value) {
            addCriterion("t_Modifier <>", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierGreaterThan(String value) {
            addCriterion("t_Modifier >", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierGreaterThanOrEqualTo(String value) {
            addCriterion("t_Modifier >=", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierLessThan(String value) {
            addCriterion("t_Modifier <", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierLessThanOrEqualTo(String value) {
            addCriterion("t_Modifier <=", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierLike(String value) {
            addCriterion("t_Modifier like", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierNotLike(String value) {
            addCriterion("t_Modifier not like", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierIn(List<String> values) {
            addCriterion("t_Modifier in", values, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierNotIn(List<String> values) {
            addCriterion("t_Modifier not in", values, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierBetween(String value1, String value2) {
            addCriterion("t_Modifier between", value1, value2, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierNotBetween(String value1, String value2) {
            addCriterion("t_Modifier not between", value1, value2, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifieripIsNull() {
            addCriterion("t_ModifierIP is null");
            return (Criteria) this;
        }

        public Criteria andTModifieripIsNotNull() {
            addCriterion("t_ModifierIP is not null");
            return (Criteria) this;
        }

        public Criteria andTModifieripEqualTo(String value) {
            addCriterion("t_ModifierIP =", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripNotEqualTo(String value) {
            addCriterion("t_ModifierIP <>", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripGreaterThan(String value) {
            addCriterion("t_ModifierIP >", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripGreaterThanOrEqualTo(String value) {
            addCriterion("t_ModifierIP >=", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripLessThan(String value) {
            addCriterion("t_ModifierIP <", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripLessThanOrEqualTo(String value) {
            addCriterion("t_ModifierIP <=", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripLike(String value) {
            addCriterion("t_ModifierIP like", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripNotLike(String value) {
            addCriterion("t_ModifierIP not like", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripIn(List<String> values) {
            addCriterion("t_ModifierIP in", values, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripNotIn(List<String> values) {
            addCriterion("t_ModifierIP not in", values, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripBetween(String value1, String value2) {
            addCriterion("t_ModifierIP between", value1, value2, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripNotBetween(String value1, String value2) {
            addCriterion("t_ModifierIP not between", value1, value2, "tModifierip");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Act
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 28 12:01:16 CST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Act
     *
     * @mbg.generated Mon Apr 28 12:01:16 CST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}