package com.kd.ci.domain.first;

import java.math.BigDecimal;
import java.util.Date;

public class Belong {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.id
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.orgUnitId
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private BigDecimal orgunitid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.personnelId
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private BigDecimal personnelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.belongType
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private Integer belongtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.subOrgUnitId
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private BigDecimal suborgunitid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.t_APModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private Date tApmodifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.t_APMotifier
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private String tApmotifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.t_APMotifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private String tApmotifierip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.t_ReceiveDate
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private Date tReceivedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.t_ReceiveSystem
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private String tReceivesystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.t_CreateDate
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private Date tCreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.t_Creator
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private String tCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.t_CreatorIP
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private String tCreatorip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.t_ModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private Date tModifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.t_Modifier
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private String tModifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Belong.t_ModifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    private String tModifierip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.id
     *
     * @return the value of Belong.id
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.id
     *
     * @param id the value for Belong.id
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.orgUnitId
     *
     * @return the value of Belong.orgUnitId
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public BigDecimal getOrgunitid() {
        return orgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.orgUnitId
     *
     * @param orgunitid the value for Belong.orgUnitId
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void setOrgunitid(BigDecimal orgunitid) {
        this.orgunitid = orgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.personnelId
     *
     * @return the value of Belong.personnelId
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public BigDecimal getPersonnelid() {
        return personnelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.personnelId
     *
     * @param personnelid the value for Belong.personnelId
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void setPersonnelid(BigDecimal personnelid) {
        this.personnelid = personnelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.belongType
     *
     * @return the value of Belong.belongType
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public Integer getBelongtype() {
        return belongtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.belongType
     *
     * @param belongtype the value for Belong.belongType
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void setBelongtype(Integer belongtype) {
        this.belongtype = belongtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.subOrgUnitId
     *
     * @return the value of Belong.subOrgUnitId
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public BigDecimal getSuborgunitid() {
        return suborgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.subOrgUnitId
     *
     * @param suborgunitid the value for Belong.subOrgUnitId
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void setSuborgunitid(BigDecimal suborgunitid) {
        this.suborgunitid = suborgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.t_APModifyDate
     *
     * @return the value of Belong.t_APModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public Date gettApmodifydate() {
        return tApmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.t_APModifyDate
     *
     * @param tApmodifydate the value for Belong.t_APModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void settApmodifydate(Date tApmodifydate) {
        this.tApmodifydate = tApmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.t_APMotifier
     *
     * @return the value of Belong.t_APMotifier
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public String gettApmotifier() {
        return tApmotifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.t_APMotifier
     *
     * @param tApmotifier the value for Belong.t_APMotifier
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void settApmotifier(String tApmotifier) {
        this.tApmotifier = tApmotifier == null ? null : tApmotifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.t_APMotifierIP
     *
     * @return the value of Belong.t_APMotifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public String gettApmotifierip() {
        return tApmotifierip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.t_APMotifierIP
     *
     * @param tApmotifierip the value for Belong.t_APMotifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void settApmotifierip(String tApmotifierip) {
        this.tApmotifierip = tApmotifierip == null ? null : tApmotifierip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.t_ReceiveDate
     *
     * @return the value of Belong.t_ReceiveDate
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public Date gettReceivedate() {
        return tReceivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.t_ReceiveDate
     *
     * @param tReceivedate the value for Belong.t_ReceiveDate
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void settReceivedate(Date tReceivedate) {
        this.tReceivedate = tReceivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.t_ReceiveSystem
     *
     * @return the value of Belong.t_ReceiveSystem
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public String gettReceivesystem() {
        return tReceivesystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.t_ReceiveSystem
     *
     * @param tReceivesystem the value for Belong.t_ReceiveSystem
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void settReceivesystem(String tReceivesystem) {
        this.tReceivesystem = tReceivesystem == null ? null : tReceivesystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.t_CreateDate
     *
     * @return the value of Belong.t_CreateDate
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public Date gettCreatedate() {
        return tCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.t_CreateDate
     *
     * @param tCreatedate the value for Belong.t_CreateDate
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void settCreatedate(Date tCreatedate) {
        this.tCreatedate = tCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.t_Creator
     *
     * @return the value of Belong.t_Creator
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public String gettCreator() {
        return tCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.t_Creator
     *
     * @param tCreator the value for Belong.t_Creator
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void settCreator(String tCreator) {
        this.tCreator = tCreator == null ? null : tCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.t_CreatorIP
     *
     * @return the value of Belong.t_CreatorIP
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public String gettCreatorip() {
        return tCreatorip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.t_CreatorIP
     *
     * @param tCreatorip the value for Belong.t_CreatorIP
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void settCreatorip(String tCreatorip) {
        this.tCreatorip = tCreatorip == null ? null : tCreatorip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.t_ModifyDate
     *
     * @return the value of Belong.t_ModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public Date gettModifydate() {
        return tModifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.t_ModifyDate
     *
     * @param tModifydate the value for Belong.t_ModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void settModifydate(Date tModifydate) {
        this.tModifydate = tModifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.t_Modifier
     *
     * @return the value of Belong.t_Modifier
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public String gettModifier() {
        return tModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.t_Modifier
     *
     * @param tModifier the value for Belong.t_Modifier
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void settModifier(String tModifier) {
        this.tModifier = tModifier == null ? null : tModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Belong.t_ModifierIP
     *
     * @return the value of Belong.t_ModifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public String gettModifierip() {
        return tModifierip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Belong.t_ModifierIP
     *
     * @param tModifierip the value for Belong.t_ModifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:15 CST 2025
     */
    public void settModifierip(String tModifierip) {
        this.tModifierip = tModifierip == null ? null : tModifierip.trim();
    }
}