package com.kd.ci.domain.first;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Menuitem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.id
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.toolTip
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private String tooltip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.name
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.location
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.title
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.position
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private BigDecimal position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.align
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private String align;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.action
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.parent_id
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private BigDecimal parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.t_APModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private Date tApmodifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.t_APMotifier
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private String tApmotifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.t_APMotifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private String tApmotifierip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.t_ReceiveDate
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private Date tReceivedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.t_ReceiveSystem
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private String tReceivesystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.t_CreateDate
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private Date tCreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.t_Creator
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private String tCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.t_CreatorIP
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private String tCreatorip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.t_ModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private Date tModifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.t_Modifier
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private String tModifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MenuItem.t_ModifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    private String tModifierip;
    
    private List<Menuitem> children;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.id
     *
     * @return the value of MenuItem.id
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.id
     *
     * @param id the value for MenuItem.id
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.toolTip
     *
     * @return the value of MenuItem.toolTip
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public String getTooltip() {
        return tooltip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.toolTip
     *
     * @param tooltip the value for MenuItem.toolTip
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void setTooltip(String tooltip) {
        this.tooltip = tooltip == null ? null : tooltip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.name
     *
     * @return the value of MenuItem.name
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.name
     *
     * @param name the value for MenuItem.name
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.location
     *
     * @return the value of MenuItem.location
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.location
     *
     * @param location the value for MenuItem.location
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.title
     *
     * @return the value of MenuItem.title
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.title
     *
     * @param title the value for MenuItem.title
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.position
     *
     * @return the value of MenuItem.position
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public BigDecimal getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.position
     *
     * @param position the value for MenuItem.position
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void setPosition(BigDecimal position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.align
     *
     * @return the value of MenuItem.align
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public String getAlign() {
        return align;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.align
     *
     * @param align the value for MenuItem.align
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void setAlign(String align) {
        this.align = align == null ? null : align.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.action
     *
     * @return the value of MenuItem.action
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.action
     *
     * @param action the value for MenuItem.action
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.parent_id
     *
     * @return the value of MenuItem.parent_id
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public BigDecimal getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.parent_id
     *
     * @param parentId the value for MenuItem.parent_id
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void setParentId(BigDecimal parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.t_APModifyDate
     *
     * @return the value of MenuItem.t_APModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public Date gettApmodifydate() {
        return tApmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.t_APModifyDate
     *
     * @param tApmodifydate the value for MenuItem.t_APModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void settApmodifydate(Date tApmodifydate) {
        this.tApmodifydate = tApmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.t_APMotifier
     *
     * @return the value of MenuItem.t_APMotifier
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public String gettApmotifier() {
        return tApmotifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.t_APMotifier
     *
     * @param tApmotifier the value for MenuItem.t_APMotifier
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void settApmotifier(String tApmotifier) {
        this.tApmotifier = tApmotifier == null ? null : tApmotifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.t_APMotifierIP
     *
     * @return the value of MenuItem.t_APMotifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public String gettApmotifierip() {
        return tApmotifierip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.t_APMotifierIP
     *
     * @param tApmotifierip the value for MenuItem.t_APMotifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void settApmotifierip(String tApmotifierip) {
        this.tApmotifierip = tApmotifierip == null ? null : tApmotifierip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.t_ReceiveDate
     *
     * @return the value of MenuItem.t_ReceiveDate
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public Date gettReceivedate() {
        return tReceivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.t_ReceiveDate
     *
     * @param tReceivedate the value for MenuItem.t_ReceiveDate
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void settReceivedate(Date tReceivedate) {
        this.tReceivedate = tReceivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.t_ReceiveSystem
     *
     * @return the value of MenuItem.t_ReceiveSystem
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public String gettReceivesystem() {
        return tReceivesystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.t_ReceiveSystem
     *
     * @param tReceivesystem the value for MenuItem.t_ReceiveSystem
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void settReceivesystem(String tReceivesystem) {
        this.tReceivesystem = tReceivesystem == null ? null : tReceivesystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.t_CreateDate
     *
     * @return the value of MenuItem.t_CreateDate
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public Date gettCreatedate() {
        return tCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.t_CreateDate
     *
     * @param tCreatedate the value for MenuItem.t_CreateDate
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void settCreatedate(Date tCreatedate) {
        this.tCreatedate = tCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.t_Creator
     *
     * @return the value of MenuItem.t_Creator
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public String gettCreator() {
        return tCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.t_Creator
     *
     * @param tCreator the value for MenuItem.t_Creator
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void settCreator(String tCreator) {
        this.tCreator = tCreator == null ? null : tCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.t_CreatorIP
     *
     * @return the value of MenuItem.t_CreatorIP
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public String gettCreatorip() {
        return tCreatorip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.t_CreatorIP
     *
     * @param tCreatorip the value for MenuItem.t_CreatorIP
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void settCreatorip(String tCreatorip) {
        this.tCreatorip = tCreatorip == null ? null : tCreatorip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.t_ModifyDate
     *
     * @return the value of MenuItem.t_ModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public Date gettModifydate() {
        return tModifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.t_ModifyDate
     *
     * @param tModifydate the value for MenuItem.t_ModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void settModifydate(Date tModifydate) {
        this.tModifydate = tModifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.t_Modifier
     *
     * @return the value of MenuItem.t_Modifier
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public String gettModifier() {
        return tModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.t_Modifier
     *
     * @param tModifier the value for MenuItem.t_Modifier
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void settModifier(String tModifier) {
        this.tModifier = tModifier == null ? null : tModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MenuItem.t_ModifierIP
     *
     * @return the value of MenuItem.t_ModifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public String gettModifierip() {
        return tModifierip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MenuItem.t_ModifierIP
     *
     * @param tModifierip the value for MenuItem.t_ModifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:11 CST 2025
     */
    public void settModifierip(String tModifierip) {
        this.tModifierip = tModifierip == null ? null : tModifierip.trim();
    }

	public List<Menuitem> getChildren() {
		return children;
	}

	public void setChildren(List<Menuitem> children) {
		this.children = children;
	}
    
    
}