package com.kd.ci.domain.first;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PersonnelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public PersonnelExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andIdnumIsNull() {
            addCriterion("idNum is null");
            return (Criteria) this;
        }

        public Criteria andIdnumIsNotNull() {
            addCriterion("idNum is not null");
            return (Criteria) this;
        }

        public Criteria andIdnumEqualTo(String value) {
            addCriterion("idNum =", value, "idnum");
            return (Criteria) this;
        }

        public Criteria andIdnumNotEqualTo(String value) {
            addCriterion("idNum <>", value, "idnum");
            return (Criteria) this;
        }

        public Criteria andIdnumGreaterThan(String value) {
            addCriterion("idNum >", value, "idnum");
            return (Criteria) this;
        }

        public Criteria andIdnumGreaterThanOrEqualTo(String value) {
            addCriterion("idNum >=", value, "idnum");
            return (Criteria) this;
        }

        public Criteria andIdnumLessThan(String value) {
            addCriterion("idNum <", value, "idnum");
            return (Criteria) this;
        }

        public Criteria andIdnumLessThanOrEqualTo(String value) {
            addCriterion("idNum <=", value, "idnum");
            return (Criteria) this;
        }

        public Criteria andIdnumLike(String value) {
            addCriterion("idNum like", value, "idnum");
            return (Criteria) this;
        }

        public Criteria andIdnumNotLike(String value) {
            addCriterion("idNum not like", value, "idnum");
            return (Criteria) this;
        }

        public Criteria andIdnumIn(List<String> values) {
            addCriterion("idNum in", values, "idnum");
            return (Criteria) this;
        }

        public Criteria andIdnumNotIn(List<String> values) {
            addCriterion("idNum not in", values, "idnum");
            return (Criteria) this;
        }

        public Criteria andIdnumBetween(String value1, String value2) {
            addCriterion("idNum between", value1, value2, "idnum");
            return (Criteria) this;
        }

        public Criteria andIdnumNotBetween(String value1, String value2) {
            addCriterion("idNum not between", value1, value2, "idnum");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("tel is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("tel is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("tel =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("tel <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("tel >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("tel >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("tel <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("tel <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("tel like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("tel not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("tel in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("tel not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("tel between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("tel not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTel2IsNull() {
            addCriterion("tel2 is null");
            return (Criteria) this;
        }

        public Criteria andTel2IsNotNull() {
            addCriterion("tel2 is not null");
            return (Criteria) this;
        }

        public Criteria andTel2EqualTo(String value) {
            addCriterion("tel2 =", value, "tel2");
            return (Criteria) this;
        }

        public Criteria andTel2NotEqualTo(String value) {
            addCriterion("tel2 <>", value, "tel2");
            return (Criteria) this;
        }

        public Criteria andTel2GreaterThan(String value) {
            addCriterion("tel2 >", value, "tel2");
            return (Criteria) this;
        }

        public Criteria andTel2GreaterThanOrEqualTo(String value) {
            addCriterion("tel2 >=", value, "tel2");
            return (Criteria) this;
        }

        public Criteria andTel2LessThan(String value) {
            addCriterion("tel2 <", value, "tel2");
            return (Criteria) this;
        }

        public Criteria andTel2LessThanOrEqualTo(String value) {
            addCriterion("tel2 <=", value, "tel2");
            return (Criteria) this;
        }

        public Criteria andTel2Like(String value) {
            addCriterion("tel2 like", value, "tel2");
            return (Criteria) this;
        }

        public Criteria andTel2NotLike(String value) {
            addCriterion("tel2 not like", value, "tel2");
            return (Criteria) this;
        }

        public Criteria andTel2In(List<String> values) {
            addCriterion("tel2 in", values, "tel2");
            return (Criteria) this;
        }

        public Criteria andTel2NotIn(List<String> values) {
            addCriterion("tel2 not in", values, "tel2");
            return (Criteria) this;
        }

        public Criteria andTel2Between(String value1, String value2) {
            addCriterion("tel2 between", value1, value2, "tel2");
            return (Criteria) this;
        }

        public Criteria andTel2NotBetween(String value1, String value2) {
            addCriterion("tel2 not between", value1, value2, "tel2");
            return (Criteria) this;
        }

        public Criteria andTitlecodeIsNull() {
            addCriterion("titleCode is null");
            return (Criteria) this;
        }

        public Criteria andTitlecodeIsNotNull() {
            addCriterion("titleCode is not null");
            return (Criteria) this;
        }

        public Criteria andTitlecodeEqualTo(String value) {
            addCriterion("titleCode =", value, "titlecode");
            return (Criteria) this;
        }

        public Criteria andTitlecodeNotEqualTo(String value) {
            addCriterion("titleCode <>", value, "titlecode");
            return (Criteria) this;
        }

        public Criteria andTitlecodeGreaterThan(String value) {
            addCriterion("titleCode >", value, "titlecode");
            return (Criteria) this;
        }

        public Criteria andTitlecodeGreaterThanOrEqualTo(String value) {
            addCriterion("titleCode >=", value, "titlecode");
            return (Criteria) this;
        }

        public Criteria andTitlecodeLessThan(String value) {
            addCriterion("titleCode <", value, "titlecode");
            return (Criteria) this;
        }

        public Criteria andTitlecodeLessThanOrEqualTo(String value) {
            addCriterion("titleCode <=", value, "titlecode");
            return (Criteria) this;
        }

        public Criteria andTitlecodeLike(String value) {
            addCriterion("titleCode like", value, "titlecode");
            return (Criteria) this;
        }

        public Criteria andTitlecodeNotLike(String value) {
            addCriterion("titleCode not like", value, "titlecode");
            return (Criteria) this;
        }

        public Criteria andTitlecodeIn(List<String> values) {
            addCriterion("titleCode in", values, "titlecode");
            return (Criteria) this;
        }

        public Criteria andTitlecodeNotIn(List<String> values) {
            addCriterion("titleCode not in", values, "titlecode");
            return (Criteria) this;
        }

        public Criteria andTitlecodeBetween(String value1, String value2) {
            addCriterion("titleCode between", value1, value2, "titlecode");
            return (Criteria) this;
        }

        public Criteria andTitlecodeNotBetween(String value1, String value2) {
            addCriterion("titleCode not between", value1, value2, "titlecode");
            return (Criteria) this;
        }

        public Criteria andTitlenameIsNull() {
            addCriterion("titleName is null");
            return (Criteria) this;
        }

        public Criteria andTitlenameIsNotNull() {
            addCriterion("titleName is not null");
            return (Criteria) this;
        }

        public Criteria andTitlenameEqualTo(String value) {
            addCriterion("titleName =", value, "titlename");
            return (Criteria) this;
        }

        public Criteria andTitlenameNotEqualTo(String value) {
            addCriterion("titleName <>", value, "titlename");
            return (Criteria) this;
        }

        public Criteria andTitlenameGreaterThan(String value) {
            addCriterion("titleName >", value, "titlename");
            return (Criteria) this;
        }

        public Criteria andTitlenameGreaterThanOrEqualTo(String value) {
            addCriterion("titleName >=", value, "titlename");
            return (Criteria) this;
        }

        public Criteria andTitlenameLessThan(String value) {
            addCriterion("titleName <", value, "titlename");
            return (Criteria) this;
        }

        public Criteria andTitlenameLessThanOrEqualTo(String value) {
            addCriterion("titleName <=", value, "titlename");
            return (Criteria) this;
        }

        public Criteria andTitlenameLike(String value) {
            addCriterion("titleName like", value, "titlename");
            return (Criteria) this;
        }

        public Criteria andTitlenameNotLike(String value) {
            addCriterion("titleName not like", value, "titlename");
            return (Criteria) this;
        }

        public Criteria andTitlenameIn(List<String> values) {
            addCriterion("titleName in", values, "titlename");
            return (Criteria) this;
        }

        public Criteria andTitlenameNotIn(List<String> values) {
            addCriterion("titleName not in", values, "titlename");
            return (Criteria) this;
        }

        public Criteria andTitlenameBetween(String value1, String value2) {
            addCriterion("titleName between", value1, value2, "titlename");
            return (Criteria) this;
        }

        public Criteria andTitlenameNotBetween(String value1, String value2) {
            addCriterion("titleName not between", value1, value2, "titlename");
            return (Criteria) this;
        }

        public Criteria andEmail1IsNull() {
            addCriterion("email1 is null");
            return (Criteria) this;
        }

        public Criteria andEmail1IsNotNull() {
            addCriterion("email1 is not null");
            return (Criteria) this;
        }

        public Criteria andEmail1EqualTo(String value) {
            addCriterion("email1 =", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1NotEqualTo(String value) {
            addCriterion("email1 <>", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1GreaterThan(String value) {
            addCriterion("email1 >", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1GreaterThanOrEqualTo(String value) {
            addCriterion("email1 >=", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1LessThan(String value) {
            addCriterion("email1 <", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1LessThanOrEqualTo(String value) {
            addCriterion("email1 <=", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1Like(String value) {
            addCriterion("email1 like", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1NotLike(String value) {
            addCriterion("email1 not like", value, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1In(List<String> values) {
            addCriterion("email1 in", values, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1NotIn(List<String> values) {
            addCriterion("email1 not in", values, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1Between(String value1, String value2) {
            addCriterion("email1 between", value1, value2, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail1NotBetween(String value1, String value2) {
            addCriterion("email1 not between", value1, value2, "email1");
            return (Criteria) this;
        }

        public Criteria andEmail2IsNull() {
            addCriterion("email2 is null");
            return (Criteria) this;
        }

        public Criteria andEmail2IsNotNull() {
            addCriterion("email2 is not null");
            return (Criteria) this;
        }

        public Criteria andEmail2EqualTo(String value) {
            addCriterion("email2 =", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2NotEqualTo(String value) {
            addCriterion("email2 <>", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2GreaterThan(String value) {
            addCriterion("email2 >", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2GreaterThanOrEqualTo(String value) {
            addCriterion("email2 >=", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2LessThan(String value) {
            addCriterion("email2 <", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2LessThanOrEqualTo(String value) {
            addCriterion("email2 <=", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2Like(String value) {
            addCriterion("email2 like", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2NotLike(String value) {
            addCriterion("email2 not like", value, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2In(List<String> values) {
            addCriterion("email2 in", values, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2NotIn(List<String> values) {
            addCriterion("email2 not in", values, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2Between(String value1, String value2) {
            addCriterion("email2 between", value1, value2, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail2NotBetween(String value1, String value2) {
            addCriterion("email2 not between", value1, value2, "email2");
            return (Criteria) this;
        }

        public Criteria andEmail3IsNull() {
            addCriterion("email3 is null");
            return (Criteria) this;
        }

        public Criteria andEmail3IsNotNull() {
            addCriterion("email3 is not null");
            return (Criteria) this;
        }

        public Criteria andEmail3EqualTo(String value) {
            addCriterion("email3 =", value, "email3");
            return (Criteria) this;
        }

        public Criteria andEmail3NotEqualTo(String value) {
            addCriterion("email3 <>", value, "email3");
            return (Criteria) this;
        }

        public Criteria andEmail3GreaterThan(String value) {
            addCriterion("email3 >", value, "email3");
            return (Criteria) this;
        }

        public Criteria andEmail3GreaterThanOrEqualTo(String value) {
            addCriterion("email3 >=", value, "email3");
            return (Criteria) this;
        }

        public Criteria andEmail3LessThan(String value) {
            addCriterion("email3 <", value, "email3");
            return (Criteria) this;
        }

        public Criteria andEmail3LessThanOrEqualTo(String value) {
            addCriterion("email3 <=", value, "email3");
            return (Criteria) this;
        }

        public Criteria andEmail3Like(String value) {
            addCriterion("email3 like", value, "email3");
            return (Criteria) this;
        }

        public Criteria andEmail3NotLike(String value) {
            addCriterion("email3 not like", value, "email3");
            return (Criteria) this;
        }

        public Criteria andEmail3In(List<String> values) {
            addCriterion("email3 in", values, "email3");
            return (Criteria) this;
        }

        public Criteria andEmail3NotIn(List<String> values) {
            addCriterion("email3 not in", values, "email3");
            return (Criteria) this;
        }

        public Criteria andEmail3Between(String value1, String value2) {
            addCriterion("email3 between", value1, value2, "email3");
            return (Criteria) this;
        }

        public Criteria andEmail3NotBetween(String value1, String value2) {
            addCriterion("email3 not between", value1, value2, "email3");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("enabled is null");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("enabled is not null");
            return (Criteria) this;
        }

        public Criteria andEnabledEqualTo(Byte value) {
            addCriterion("enabled =", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotEqualTo(Byte value) {
            addCriterion("enabled <>", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThan(Byte value) {
            addCriterion("enabled >", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(Byte value) {
            addCriterion("enabled >=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThan(Byte value) {
            addCriterion("enabled <", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThanOrEqualTo(Byte value) {
            addCriterion("enabled <=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledIn(List<Byte> values) {
            addCriterion("enabled in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotIn(List<Byte> values) {
            addCriterion("enabled not in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledBetween(Byte value1, Byte value2) {
            addCriterion("enabled between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotBetween(Byte value1, Byte value2) {
            addCriterion("enabled not between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andEaccountIsNull() {
            addCriterion("eaccount is null");
            return (Criteria) this;
        }

        public Criteria andEaccountIsNotNull() {
            addCriterion("eaccount is not null");
            return (Criteria) this;
        }

        public Criteria andEaccountEqualTo(String value) {
            addCriterion("eaccount =", value, "eaccount");
            return (Criteria) this;
        }

        public Criteria andEaccountNotEqualTo(String value) {
            addCriterion("eaccount <>", value, "eaccount");
            return (Criteria) this;
        }

        public Criteria andEaccountGreaterThan(String value) {
            addCriterion("eaccount >", value, "eaccount");
            return (Criteria) this;
        }

        public Criteria andEaccountGreaterThanOrEqualTo(String value) {
            addCriterion("eaccount >=", value, "eaccount");
            return (Criteria) this;
        }

        public Criteria andEaccountLessThan(String value) {
            addCriterion("eaccount <", value, "eaccount");
            return (Criteria) this;
        }

        public Criteria andEaccountLessThanOrEqualTo(String value) {
            addCriterion("eaccount <=", value, "eaccount");
            return (Criteria) this;
        }

        public Criteria andEaccountLike(String value) {
            addCriterion("eaccount like", value, "eaccount");
            return (Criteria) this;
        }

        public Criteria andEaccountNotLike(String value) {
            addCriterion("eaccount not like", value, "eaccount");
            return (Criteria) this;
        }

        public Criteria andEaccountIn(List<String> values) {
            addCriterion("eaccount in", values, "eaccount");
            return (Criteria) this;
        }

        public Criteria andEaccountNotIn(List<String> values) {
            addCriterion("eaccount not in", values, "eaccount");
            return (Criteria) this;
        }

        public Criteria andEaccountBetween(String value1, String value2) {
            addCriterion("eaccount between", value1, value2, "eaccount");
            return (Criteria) this;
        }

        public Criteria andEaccountNotBetween(String value1, String value2) {
            addCriterion("eaccount not between", value1, value2, "eaccount");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNull() {
            addCriterion("startDate is null");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNotNull() {
            addCriterion("startDate is not null");
            return (Criteria) this;
        }

        public Criteria andStartdateEqualTo(Date value) {
            addCriterion("startDate =", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotEqualTo(Date value) {
            addCriterion("startDate <>", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThan(Date value) {
            addCriterion("startDate >", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThanOrEqualTo(Date value) {
            addCriterion("startDate >=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThan(Date value) {
            addCriterion("startDate <", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThanOrEqualTo(Date value) {
            addCriterion("startDate <=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIn(List<Date> values) {
            addCriterion("startDate in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotIn(List<Date> values) {
            addCriterion("startDate not in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateBetween(Date value1, Date value2) {
            addCriterion("startDate between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotBetween(Date value1, Date value2) {
            addCriterion("startDate not between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNull() {
            addCriterion("endDate is null");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNotNull() {
            addCriterion("endDate is not null");
            return (Criteria) this;
        }

        public Criteria andEnddateEqualTo(Date value) {
            addCriterion("endDate =", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotEqualTo(Date value) {
            addCriterion("endDate <>", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThan(Date value) {
            addCriterion("endDate >", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThanOrEqualTo(Date value) {
            addCriterion("endDate >=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThan(Date value) {
            addCriterion("endDate <", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThanOrEqualTo(Date value) {
            addCriterion("endDate <=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateIn(List<Date> values) {
            addCriterion("endDate in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotIn(List<Date> values) {
            addCriterion("endDate not in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateBetween(Date value1, Date value2) {
            addCriterion("endDate between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotBetween(Date value1, Date value2) {
            addCriterion("endDate not between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andLoginipIsNull() {
            addCriterion("loginIP is null");
            return (Criteria) this;
        }

        public Criteria andLoginipIsNotNull() {
            addCriterion("loginIP is not null");
            return (Criteria) this;
        }

        public Criteria andLoginipEqualTo(String value) {
            addCriterion("loginIP =", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipNotEqualTo(String value) {
            addCriterion("loginIP <>", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipGreaterThan(String value) {
            addCriterion("loginIP >", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipGreaterThanOrEqualTo(String value) {
            addCriterion("loginIP >=", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipLessThan(String value) {
            addCriterion("loginIP <", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipLessThanOrEqualTo(String value) {
            addCriterion("loginIP <=", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipLike(String value) {
            addCriterion("loginIP like", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipNotLike(String value) {
            addCriterion("loginIP not like", value, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipIn(List<String> values) {
            addCriterion("loginIP in", values, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipNotIn(List<String> values) {
            addCriterion("loginIP not in", values, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipBetween(String value1, String value2) {
            addCriterion("loginIP between", value1, value2, "loginip");
            return (Criteria) this;
        }

        public Criteria andLoginipNotBetween(String value1, String value2) {
            addCriterion("loginIP not between", value1, value2, "loginip");
            return (Criteria) this;
        }

        public Criteria andSsokeyIsNull() {
            addCriterion("ssoKey is null");
            return (Criteria) this;
        }

        public Criteria andSsokeyIsNotNull() {
            addCriterion("ssoKey is not null");
            return (Criteria) this;
        }

        public Criteria andSsokeyEqualTo(String value) {
            addCriterion("ssoKey =", value, "ssokey");
            return (Criteria) this;
        }

        public Criteria andSsokeyNotEqualTo(String value) {
            addCriterion("ssoKey <>", value, "ssokey");
            return (Criteria) this;
        }

        public Criteria andSsokeyGreaterThan(String value) {
            addCriterion("ssoKey >", value, "ssokey");
            return (Criteria) this;
        }

        public Criteria andSsokeyGreaterThanOrEqualTo(String value) {
            addCriterion("ssoKey >=", value, "ssokey");
            return (Criteria) this;
        }

        public Criteria andSsokeyLessThan(String value) {
            addCriterion("ssoKey <", value, "ssokey");
            return (Criteria) this;
        }

        public Criteria andSsokeyLessThanOrEqualTo(String value) {
            addCriterion("ssoKey <=", value, "ssokey");
            return (Criteria) this;
        }

        public Criteria andSsokeyLike(String value) {
            addCriterion("ssoKey like", value, "ssokey");
            return (Criteria) this;
        }

        public Criteria andSsokeyNotLike(String value) {
            addCriterion("ssoKey not like", value, "ssokey");
            return (Criteria) this;
        }

        public Criteria andSsokeyIn(List<String> values) {
            addCriterion("ssoKey in", values, "ssokey");
            return (Criteria) this;
        }

        public Criteria andSsokeyNotIn(List<String> values) {
            addCriterion("ssoKey not in", values, "ssokey");
            return (Criteria) this;
        }

        public Criteria andSsokeyBetween(String value1, String value2) {
            addCriterion("ssoKey between", value1, value2, "ssokey");
            return (Criteria) this;
        }

        public Criteria andSsokeyNotBetween(String value1, String value2) {
            addCriterion("ssoKey not between", value1, value2, "ssokey");
            return (Criteria) this;
        }

        public Criteria andInformemail1IsNull() {
            addCriterion("informEmail1 is null");
            return (Criteria) this;
        }

        public Criteria andInformemail1IsNotNull() {
            addCriterion("informEmail1 is not null");
            return (Criteria) this;
        }

        public Criteria andInformemail1EqualTo(String value) {
            addCriterion("informEmail1 =", value, "informemail1");
            return (Criteria) this;
        }

        public Criteria andInformemail1NotEqualTo(String value) {
            addCriterion("informEmail1 <>", value, "informemail1");
            return (Criteria) this;
        }

        public Criteria andInformemail1GreaterThan(String value) {
            addCriterion("informEmail1 >", value, "informemail1");
            return (Criteria) this;
        }

        public Criteria andInformemail1GreaterThanOrEqualTo(String value) {
            addCriterion("informEmail1 >=", value, "informemail1");
            return (Criteria) this;
        }

        public Criteria andInformemail1LessThan(String value) {
            addCriterion("informEmail1 <", value, "informemail1");
            return (Criteria) this;
        }

        public Criteria andInformemail1LessThanOrEqualTo(String value) {
            addCriterion("informEmail1 <=", value, "informemail1");
            return (Criteria) this;
        }

        public Criteria andInformemail1Like(String value) {
            addCriterion("informEmail1 like", value, "informemail1");
            return (Criteria) this;
        }

        public Criteria andInformemail1NotLike(String value) {
            addCriterion("informEmail1 not like", value, "informemail1");
            return (Criteria) this;
        }

        public Criteria andInformemail1In(List<String> values) {
            addCriterion("informEmail1 in", values, "informemail1");
            return (Criteria) this;
        }

        public Criteria andInformemail1NotIn(List<String> values) {
            addCriterion("informEmail1 not in", values, "informemail1");
            return (Criteria) this;
        }

        public Criteria andInformemail1Between(String value1, String value2) {
            addCriterion("informEmail1 between", value1, value2, "informemail1");
            return (Criteria) this;
        }

        public Criteria andInformemail1NotBetween(String value1, String value2) {
            addCriterion("informEmail1 not between", value1, value2, "informemail1");
            return (Criteria) this;
        }

        public Criteria andInformemail2IsNull() {
            addCriterion("informEmail2 is null");
            return (Criteria) this;
        }

        public Criteria andInformemail2IsNotNull() {
            addCriterion("informEmail2 is not null");
            return (Criteria) this;
        }

        public Criteria andInformemail2EqualTo(String value) {
            addCriterion("informEmail2 =", value, "informemail2");
            return (Criteria) this;
        }

        public Criteria andInformemail2NotEqualTo(String value) {
            addCriterion("informEmail2 <>", value, "informemail2");
            return (Criteria) this;
        }

        public Criteria andInformemail2GreaterThan(String value) {
            addCriterion("informEmail2 >", value, "informemail2");
            return (Criteria) this;
        }

        public Criteria andInformemail2GreaterThanOrEqualTo(String value) {
            addCriterion("informEmail2 >=", value, "informemail2");
            return (Criteria) this;
        }

        public Criteria andInformemail2LessThan(String value) {
            addCriterion("informEmail2 <", value, "informemail2");
            return (Criteria) this;
        }

        public Criteria andInformemail2LessThanOrEqualTo(String value) {
            addCriterion("informEmail2 <=", value, "informemail2");
            return (Criteria) this;
        }

        public Criteria andInformemail2Like(String value) {
            addCriterion("informEmail2 like", value, "informemail2");
            return (Criteria) this;
        }

        public Criteria andInformemail2NotLike(String value) {
            addCriterion("informEmail2 not like", value, "informemail2");
            return (Criteria) this;
        }

        public Criteria andInformemail2In(List<String> values) {
            addCriterion("informEmail2 in", values, "informemail2");
            return (Criteria) this;
        }

        public Criteria andInformemail2NotIn(List<String> values) {
            addCriterion("informEmail2 not in", values, "informemail2");
            return (Criteria) this;
        }

        public Criteria andInformemail2Between(String value1, String value2) {
            addCriterion("informEmail2 between", value1, value2, "informemail2");
            return (Criteria) this;
        }

        public Criteria andInformemail2NotBetween(String value1, String value2) {
            addCriterion("informEmail2 not between", value1, value2, "informemail2");
            return (Criteria) this;
        }

        public Criteria andInformmobileIsNull() {
            addCriterion("informMobile is null");
            return (Criteria) this;
        }

        public Criteria andInformmobileIsNotNull() {
            addCriterion("informMobile is not null");
            return (Criteria) this;
        }

        public Criteria andInformmobileEqualTo(String value) {
            addCriterion("informMobile =", value, "informmobile");
            return (Criteria) this;
        }

        public Criteria andInformmobileNotEqualTo(String value) {
            addCriterion("informMobile <>", value, "informmobile");
            return (Criteria) this;
        }

        public Criteria andInformmobileGreaterThan(String value) {
            addCriterion("informMobile >", value, "informmobile");
            return (Criteria) this;
        }

        public Criteria andInformmobileGreaterThanOrEqualTo(String value) {
            addCriterion("informMobile >=", value, "informmobile");
            return (Criteria) this;
        }

        public Criteria andInformmobileLessThan(String value) {
            addCriterion("informMobile <", value, "informmobile");
            return (Criteria) this;
        }

        public Criteria andInformmobileLessThanOrEqualTo(String value) {
            addCriterion("informMobile <=", value, "informmobile");
            return (Criteria) this;
        }

        public Criteria andInformmobileLike(String value) {
            addCriterion("informMobile like", value, "informmobile");
            return (Criteria) this;
        }

        public Criteria andInformmobileNotLike(String value) {
            addCriterion("informMobile not like", value, "informmobile");
            return (Criteria) this;
        }

        public Criteria andInformmobileIn(List<String> values) {
            addCriterion("informMobile in", values, "informmobile");
            return (Criteria) this;
        }

        public Criteria andInformmobileNotIn(List<String> values) {
            addCriterion("informMobile not in", values, "informmobile");
            return (Criteria) this;
        }

        public Criteria andInformmobileBetween(String value1, String value2) {
            addCriterion("informMobile between", value1, value2, "informmobile");
            return (Criteria) this;
        }

        public Criteria andInformmobileNotBetween(String value1, String value2) {
            addCriterion("informMobile not between", value1, value2, "informmobile");
            return (Criteria) this;
        }

        public Criteria andBkidnumIsNull() {
            addCriterion("bkIdNum is null");
            return (Criteria) this;
        }

        public Criteria andBkidnumIsNotNull() {
            addCriterion("bkIdNum is not null");
            return (Criteria) this;
        }

        public Criteria andBkidnumEqualTo(String value) {
            addCriterion("bkIdNum =", value, "bkidnum");
            return (Criteria) this;
        }

        public Criteria andBkidnumNotEqualTo(String value) {
            addCriterion("bkIdNum <>", value, "bkidnum");
            return (Criteria) this;
        }

        public Criteria andBkidnumGreaterThan(String value) {
            addCriterion("bkIdNum >", value, "bkidnum");
            return (Criteria) this;
        }

        public Criteria andBkidnumGreaterThanOrEqualTo(String value) {
            addCriterion("bkIdNum >=", value, "bkidnum");
            return (Criteria) this;
        }

        public Criteria andBkidnumLessThan(String value) {
            addCriterion("bkIdNum <", value, "bkidnum");
            return (Criteria) this;
        }

        public Criteria andBkidnumLessThanOrEqualTo(String value) {
            addCriterion("bkIdNum <=", value, "bkidnum");
            return (Criteria) this;
        }

        public Criteria andBkidnumLike(String value) {
            addCriterion("bkIdNum like", value, "bkidnum");
            return (Criteria) this;
        }

        public Criteria andBkidnumNotLike(String value) {
            addCriterion("bkIdNum not like", value, "bkidnum");
            return (Criteria) this;
        }

        public Criteria andBkidnumIn(List<String> values) {
            addCriterion("bkIdNum in", values, "bkidnum");
            return (Criteria) this;
        }

        public Criteria andBkidnumNotIn(List<String> values) {
            addCriterion("bkIdNum not in", values, "bkidnum");
            return (Criteria) this;
        }

        public Criteria andBkidnumBetween(String value1, String value2) {
            addCriterion("bkIdNum between", value1, value2, "bkidnum");
            return (Criteria) this;
        }

        public Criteria andBkidnumNotBetween(String value1, String value2) {
            addCriterion("bkIdNum not between", value1, value2, "bkidnum");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(String value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(String value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(String value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(String value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(String value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(String value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLike(String value) {
            addCriterion("pid like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotLike(String value) {
            addCriterion("pid not like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<String> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<String> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(String value1, String value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(String value1, String value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andGroupnumIsNull() {
            addCriterion("groupNum is null");
            return (Criteria) this;
        }

        public Criteria andGroupnumIsNotNull() {
            addCriterion("groupNum is not null");
            return (Criteria) this;
        }

        public Criteria andGroupnumEqualTo(Integer value) {
            addCriterion("groupNum =", value, "groupnum");
            return (Criteria) this;
        }

        public Criteria andGroupnumNotEqualTo(Integer value) {
            addCriterion("groupNum <>", value, "groupnum");
            return (Criteria) this;
        }

        public Criteria andGroupnumGreaterThan(Integer value) {
            addCriterion("groupNum >", value, "groupnum");
            return (Criteria) this;
        }

        public Criteria andGroupnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("groupNum >=", value, "groupnum");
            return (Criteria) this;
        }

        public Criteria andGroupnumLessThan(Integer value) {
            addCriterion("groupNum <", value, "groupnum");
            return (Criteria) this;
        }

        public Criteria andGroupnumLessThanOrEqualTo(Integer value) {
            addCriterion("groupNum <=", value, "groupnum");
            return (Criteria) this;
        }

        public Criteria andGroupnumIn(List<Integer> values) {
            addCriterion("groupNum in", values, "groupnum");
            return (Criteria) this;
        }

        public Criteria andGroupnumNotIn(List<Integer> values) {
            addCriterion("groupNum not in", values, "groupnum");
            return (Criteria) this;
        }

        public Criteria andGroupnumBetween(Integer value1, Integer value2) {
            addCriterion("groupNum between", value1, value2, "groupnum");
            return (Criteria) this;
        }

        public Criteria andGroupnumNotBetween(Integer value1, Integer value2) {
            addCriterion("groupNum not between", value1, value2, "groupnum");
            return (Criteria) this;
        }

        public Criteria andIschangpwdIsNull() {
            addCriterion("isChangPwd is null");
            return (Criteria) this;
        }

        public Criteria andIschangpwdIsNotNull() {
            addCriterion("isChangPwd is not null");
            return (Criteria) this;
        }

        public Criteria andIschangpwdEqualTo(String value) {
            addCriterion("isChangPwd =", value, "ischangpwd");
            return (Criteria) this;
        }

        public Criteria andIschangpwdNotEqualTo(String value) {
            addCriterion("isChangPwd <>", value, "ischangpwd");
            return (Criteria) this;
        }

        public Criteria andIschangpwdGreaterThan(String value) {
            addCriterion("isChangPwd >", value, "ischangpwd");
            return (Criteria) this;
        }

        public Criteria andIschangpwdGreaterThanOrEqualTo(String value) {
            addCriterion("isChangPwd >=", value, "ischangpwd");
            return (Criteria) this;
        }

        public Criteria andIschangpwdLessThan(String value) {
            addCriterion("isChangPwd <", value, "ischangpwd");
            return (Criteria) this;
        }

        public Criteria andIschangpwdLessThanOrEqualTo(String value) {
            addCriterion("isChangPwd <=", value, "ischangpwd");
            return (Criteria) this;
        }

        public Criteria andIschangpwdLike(String value) {
            addCriterion("isChangPwd like", value, "ischangpwd");
            return (Criteria) this;
        }

        public Criteria andIschangpwdNotLike(String value) {
            addCriterion("isChangPwd not like", value, "ischangpwd");
            return (Criteria) this;
        }

        public Criteria andIschangpwdIn(List<String> values) {
            addCriterion("isChangPwd in", values, "ischangpwd");
            return (Criteria) this;
        }

        public Criteria andIschangpwdNotIn(List<String> values) {
            addCriterion("isChangPwd not in", values, "ischangpwd");
            return (Criteria) this;
        }

        public Criteria andIschangpwdBetween(String value1, String value2) {
            addCriterion("isChangPwd between", value1, value2, "ischangpwd");
            return (Criteria) this;
        }

        public Criteria andIschangpwdNotBetween(String value1, String value2) {
            addCriterion("isChangPwd not between", value1, value2, "ischangpwd");
            return (Criteria) this;
        }

        public Criteria andTCreatedateIsNull() {
            addCriterion("T_CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andTCreatedateIsNotNull() {
            addCriterion("T_CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andTCreatedateEqualTo(Date value) {
            addCriterion("T_CREATEDATE =", value, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateNotEqualTo(Date value) {
            addCriterion("T_CREATEDATE <>", value, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateGreaterThan(Date value) {
            addCriterion("T_CREATEDATE >", value, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("T_CREATEDATE >=", value, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateLessThan(Date value) {
            addCriterion("T_CREATEDATE <", value, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("T_CREATEDATE <=", value, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateIn(List<Date> values) {
            addCriterion("T_CREATEDATE in", values, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateNotIn(List<Date> values) {
            addCriterion("T_CREATEDATE not in", values, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateBetween(Date value1, Date value2) {
            addCriterion("T_CREATEDATE between", value1, value2, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andTCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("T_CREATEDATE not between", value1, value2, "tCreatedate");
            return (Criteria) this;
        }

        public Criteria andIsnewIsNull() {
            addCriterion("isNew is null");
            return (Criteria) this;
        }

        public Criteria andIsnewIsNotNull() {
            addCriterion("isNew is not null");
            return (Criteria) this;
        }

        public Criteria andIsnewEqualTo(String value) {
            addCriterion("isNew =", value, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewNotEqualTo(String value) {
            addCriterion("isNew <>", value, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewGreaterThan(String value) {
            addCriterion("isNew >", value, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewGreaterThanOrEqualTo(String value) {
            addCriterion("isNew >=", value, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewLessThan(String value) {
            addCriterion("isNew <", value, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewLessThanOrEqualTo(String value) {
            addCriterion("isNew <=", value, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewLike(String value) {
            addCriterion("isNew like", value, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewNotLike(String value) {
            addCriterion("isNew not like", value, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewIn(List<String> values) {
            addCriterion("isNew in", values, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewNotIn(List<String> values) {
            addCriterion("isNew not in", values, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewBetween(String value1, String value2) {
            addCriterion("isNew between", value1, value2, "isnew");
            return (Criteria) this;
        }

        public Criteria andIsnewNotBetween(String value1, String value2) {
            addCriterion("isNew not between", value1, value2, "isnew");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateIsNull() {
            addCriterion("t_APModifyDate is null");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateIsNotNull() {
            addCriterion("t_APModifyDate is not null");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateEqualTo(Date value) {
            addCriterion("t_APModifyDate =", value, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateNotEqualTo(Date value) {
            addCriterion("t_APModifyDate <>", value, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateGreaterThan(Date value) {
            addCriterion("t_APModifyDate >", value, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("t_APModifyDate >=", value, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateLessThan(Date value) {
            addCriterion("t_APModifyDate <", value, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateLessThanOrEqualTo(Date value) {
            addCriterion("t_APModifyDate <=", value, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateIn(List<Date> values) {
            addCriterion("t_APModifyDate in", values, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateNotIn(List<Date> values) {
            addCriterion("t_APModifyDate not in", values, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateBetween(Date value1, Date value2) {
            addCriterion("t_APModifyDate between", value1, value2, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmodifydateNotBetween(Date value1, Date value2) {
            addCriterion("t_APModifyDate not between", value1, value2, "tApmodifydate");
            return (Criteria) this;
        }

        public Criteria andTApmotifierIsNull() {
            addCriterion("t_APMotifier is null");
            return (Criteria) this;
        }

        public Criteria andTApmotifierIsNotNull() {
            addCriterion("t_APMotifier is not null");
            return (Criteria) this;
        }

        public Criteria andTApmotifierEqualTo(String value) {
            addCriterion("t_APMotifier =", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierNotEqualTo(String value) {
            addCriterion("t_APMotifier <>", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierGreaterThan(String value) {
            addCriterion("t_APMotifier >", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierGreaterThanOrEqualTo(String value) {
            addCriterion("t_APMotifier >=", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierLessThan(String value) {
            addCriterion("t_APMotifier <", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierLessThanOrEqualTo(String value) {
            addCriterion("t_APMotifier <=", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierLike(String value) {
            addCriterion("t_APMotifier like", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierNotLike(String value) {
            addCriterion("t_APMotifier not like", value, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierIn(List<String> values) {
            addCriterion("t_APMotifier in", values, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierNotIn(List<String> values) {
            addCriterion("t_APMotifier not in", values, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierBetween(String value1, String value2) {
            addCriterion("t_APMotifier between", value1, value2, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifierNotBetween(String value1, String value2) {
            addCriterion("t_APMotifier not between", value1, value2, "tApmotifier");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripIsNull() {
            addCriterion("t_APMotifierIP is null");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripIsNotNull() {
            addCriterion("t_APMotifierIP is not null");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripEqualTo(String value) {
            addCriterion("t_APMotifierIP =", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripNotEqualTo(String value) {
            addCriterion("t_APMotifierIP <>", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripGreaterThan(String value) {
            addCriterion("t_APMotifierIP >", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripGreaterThanOrEqualTo(String value) {
            addCriterion("t_APMotifierIP >=", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripLessThan(String value) {
            addCriterion("t_APMotifierIP <", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripLessThanOrEqualTo(String value) {
            addCriterion("t_APMotifierIP <=", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripLike(String value) {
            addCriterion("t_APMotifierIP like", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripNotLike(String value) {
            addCriterion("t_APMotifierIP not like", value, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripIn(List<String> values) {
            addCriterion("t_APMotifierIP in", values, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripNotIn(List<String> values) {
            addCriterion("t_APMotifierIP not in", values, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripBetween(String value1, String value2) {
            addCriterion("t_APMotifierIP between", value1, value2, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTApmotifieripNotBetween(String value1, String value2) {
            addCriterion("t_APMotifierIP not between", value1, value2, "tApmotifierip");
            return (Criteria) this;
        }

        public Criteria andTReceivedateIsNull() {
            addCriterion("t_ReceiveDate is null");
            return (Criteria) this;
        }

        public Criteria andTReceivedateIsNotNull() {
            addCriterion("t_ReceiveDate is not null");
            return (Criteria) this;
        }

        public Criteria andTReceivedateEqualTo(Date value) {
            addCriterion("t_ReceiveDate =", value, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateNotEqualTo(Date value) {
            addCriterion("t_ReceiveDate <>", value, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateGreaterThan(Date value) {
            addCriterion("t_ReceiveDate >", value, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateGreaterThanOrEqualTo(Date value) {
            addCriterion("t_ReceiveDate >=", value, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateLessThan(Date value) {
            addCriterion("t_ReceiveDate <", value, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateLessThanOrEqualTo(Date value) {
            addCriterion("t_ReceiveDate <=", value, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateIn(List<Date> values) {
            addCriterion("t_ReceiveDate in", values, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateNotIn(List<Date> values) {
            addCriterion("t_ReceiveDate not in", values, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateBetween(Date value1, Date value2) {
            addCriterion("t_ReceiveDate between", value1, value2, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivedateNotBetween(Date value1, Date value2) {
            addCriterion("t_ReceiveDate not between", value1, value2, "tReceivedate");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemIsNull() {
            addCriterion("t_ReceiveSystem is null");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemIsNotNull() {
            addCriterion("t_ReceiveSystem is not null");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemEqualTo(String value) {
            addCriterion("t_ReceiveSystem =", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemNotEqualTo(String value) {
            addCriterion("t_ReceiveSystem <>", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemGreaterThan(String value) {
            addCriterion("t_ReceiveSystem >", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemGreaterThanOrEqualTo(String value) {
            addCriterion("t_ReceiveSystem >=", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemLessThan(String value) {
            addCriterion("t_ReceiveSystem <", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemLessThanOrEqualTo(String value) {
            addCriterion("t_ReceiveSystem <=", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemLike(String value) {
            addCriterion("t_ReceiveSystem like", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemNotLike(String value) {
            addCriterion("t_ReceiveSystem not like", value, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemIn(List<String> values) {
            addCriterion("t_ReceiveSystem in", values, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemNotIn(List<String> values) {
            addCriterion("t_ReceiveSystem not in", values, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemBetween(String value1, String value2) {
            addCriterion("t_ReceiveSystem between", value1, value2, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTReceivesystemNotBetween(String value1, String value2) {
            addCriterion("t_ReceiveSystem not between", value1, value2, "tReceivesystem");
            return (Criteria) this;
        }

        public Criteria andTCreatorIsNull() {
            addCriterion("t_Creator is null");
            return (Criteria) this;
        }

        public Criteria andTCreatorIsNotNull() {
            addCriterion("t_Creator is not null");
            return (Criteria) this;
        }

        public Criteria andTCreatorEqualTo(String value) {
            addCriterion("t_Creator =", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorNotEqualTo(String value) {
            addCriterion("t_Creator <>", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorGreaterThan(String value) {
            addCriterion("t_Creator >", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("t_Creator >=", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorLessThan(String value) {
            addCriterion("t_Creator <", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorLessThanOrEqualTo(String value) {
            addCriterion("t_Creator <=", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorLike(String value) {
            addCriterion("t_Creator like", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorNotLike(String value) {
            addCriterion("t_Creator not like", value, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorIn(List<String> values) {
            addCriterion("t_Creator in", values, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorNotIn(List<String> values) {
            addCriterion("t_Creator not in", values, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorBetween(String value1, String value2) {
            addCriterion("t_Creator between", value1, value2, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatorNotBetween(String value1, String value2) {
            addCriterion("t_Creator not between", value1, value2, "tCreator");
            return (Criteria) this;
        }

        public Criteria andTCreatoripIsNull() {
            addCriterion("t_CreatorIP is null");
            return (Criteria) this;
        }

        public Criteria andTCreatoripIsNotNull() {
            addCriterion("t_CreatorIP is not null");
            return (Criteria) this;
        }

        public Criteria andTCreatoripEqualTo(String value) {
            addCriterion("t_CreatorIP =", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripNotEqualTo(String value) {
            addCriterion("t_CreatorIP <>", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripGreaterThan(String value) {
            addCriterion("t_CreatorIP >", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripGreaterThanOrEqualTo(String value) {
            addCriterion("t_CreatorIP >=", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripLessThan(String value) {
            addCriterion("t_CreatorIP <", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripLessThanOrEqualTo(String value) {
            addCriterion("t_CreatorIP <=", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripLike(String value) {
            addCriterion("t_CreatorIP like", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripNotLike(String value) {
            addCriterion("t_CreatorIP not like", value, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripIn(List<String> values) {
            addCriterion("t_CreatorIP in", values, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripNotIn(List<String> values) {
            addCriterion("t_CreatorIP not in", values, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripBetween(String value1, String value2) {
            addCriterion("t_CreatorIP between", value1, value2, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTCreatoripNotBetween(String value1, String value2) {
            addCriterion("t_CreatorIP not between", value1, value2, "tCreatorip");
            return (Criteria) this;
        }

        public Criteria andTModifydateIsNull() {
            addCriterion("t_ModifyDate is null");
            return (Criteria) this;
        }

        public Criteria andTModifydateIsNotNull() {
            addCriterion("t_ModifyDate is not null");
            return (Criteria) this;
        }

        public Criteria andTModifydateEqualTo(Date value) {
            addCriterion("t_ModifyDate =", value, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateNotEqualTo(Date value) {
            addCriterion("t_ModifyDate <>", value, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateGreaterThan(Date value) {
            addCriterion("t_ModifyDate >", value, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("t_ModifyDate >=", value, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateLessThan(Date value) {
            addCriterion("t_ModifyDate <", value, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateLessThanOrEqualTo(Date value) {
            addCriterion("t_ModifyDate <=", value, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateIn(List<Date> values) {
            addCriterion("t_ModifyDate in", values, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateNotIn(List<Date> values) {
            addCriterion("t_ModifyDate not in", values, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateBetween(Date value1, Date value2) {
            addCriterion("t_ModifyDate between", value1, value2, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifydateNotBetween(Date value1, Date value2) {
            addCriterion("t_ModifyDate not between", value1, value2, "tModifydate");
            return (Criteria) this;
        }

        public Criteria andTModifierIsNull() {
            addCriterion("t_Modifier is null");
            return (Criteria) this;
        }

        public Criteria andTModifierIsNotNull() {
            addCriterion("t_Modifier is not null");
            return (Criteria) this;
        }

        public Criteria andTModifierEqualTo(String value) {
            addCriterion("t_Modifier =", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierNotEqualTo(String value) {
            addCriterion("t_Modifier <>", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierGreaterThan(String value) {
            addCriterion("t_Modifier >", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierGreaterThanOrEqualTo(String value) {
            addCriterion("t_Modifier >=", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierLessThan(String value) {
            addCriterion("t_Modifier <", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierLessThanOrEqualTo(String value) {
            addCriterion("t_Modifier <=", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierLike(String value) {
            addCriterion("t_Modifier like", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierNotLike(String value) {
            addCriterion("t_Modifier not like", value, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierIn(List<String> values) {
            addCriterion("t_Modifier in", values, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierNotIn(List<String> values) {
            addCriterion("t_Modifier not in", values, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierBetween(String value1, String value2) {
            addCriterion("t_Modifier between", value1, value2, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifierNotBetween(String value1, String value2) {
            addCriterion("t_Modifier not between", value1, value2, "tModifier");
            return (Criteria) this;
        }

        public Criteria andTModifieripIsNull() {
            addCriterion("t_ModifierIP is null");
            return (Criteria) this;
        }

        public Criteria andTModifieripIsNotNull() {
            addCriterion("t_ModifierIP is not null");
            return (Criteria) this;
        }

        public Criteria andTModifieripEqualTo(String value) {
            addCriterion("t_ModifierIP =", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripNotEqualTo(String value) {
            addCriterion("t_ModifierIP <>", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripGreaterThan(String value) {
            addCriterion("t_ModifierIP >", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripGreaterThanOrEqualTo(String value) {
            addCriterion("t_ModifierIP >=", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripLessThan(String value) {
            addCriterion("t_ModifierIP <", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripLessThanOrEqualTo(String value) {
            addCriterion("t_ModifierIP <=", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripLike(String value) {
            addCriterion("t_ModifierIP like", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripNotLike(String value) {
            addCriterion("t_ModifierIP not like", value, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripIn(List<String> values) {
            addCriterion("t_ModifierIP in", values, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripNotIn(List<String> values) {
            addCriterion("t_ModifierIP not in", values, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripBetween(String value1, String value2) {
            addCriterion("t_ModifierIP between", value1, value2, "tModifierip");
            return (Criteria) this;
        }

        public Criteria andTModifieripNotBetween(String value1, String value2) {
            addCriterion("t_ModifierIP not between", value1, value2, "tModifierip");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Personnel
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 28 12:01:19 CST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Personnel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}