package com.kd.ci.domain.first;

import java.math.BigDecimal;
import java.util.Date;

public class Personnel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.id
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.code
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.idNum
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String idnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.name
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.tel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.tel2
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String tel2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.titleCode
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String titlecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.titleName
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String titlename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.email1
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String email1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.email2
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String email2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.email3
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String email3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.password
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.enabled
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private Byte enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.eaccount
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String eaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.mobile
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.startDate
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.endDate
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.loginIP
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String loginip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.ssoKey
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String ssokey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.informEmail1
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String informemail1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.informEmail2
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String informemail2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.informMobile
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String informmobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.bkIdNum
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String bkidnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.pid
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.groupNum
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private Integer groupnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.isChangPwd
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String ischangpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.T_CREATEDATE
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private Date tCreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.isNew
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String isnew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.t_APModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private Date tApmodifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.t_APMotifier
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String tApmotifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.t_APMotifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String tApmotifierip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.t_ReceiveDate
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private Date tReceivedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.t_ReceiveSystem
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String tReceivesystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.t_Creator
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String tCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.t_CreatorIP
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String tCreatorip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.t_ModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private Date tModifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.t_Modifier
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String tModifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Personnel.t_ModifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    private String tModifierip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.id
     *
     * @return the value of Personnel.id
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.id
     *
     * @param id the value for Personnel.id
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.code
     *
     * @return the value of Personnel.code
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.code
     *
     * @param code the value for Personnel.code
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.idNum
     *
     * @return the value of Personnel.idNum
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getIdnum() {
        return idnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.idNum
     *
     * @param idnum the value for Personnel.idNum
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setIdnum(String idnum) {
        this.idnum = idnum == null ? null : idnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.name
     *
     * @return the value of Personnel.name
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.name
     *
     * @param name the value for Personnel.name
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.tel
     *
     * @return the value of Personnel.tel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.tel
     *
     * @param tel the value for Personnel.tel
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.tel2
     *
     * @return the value of Personnel.tel2
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getTel2() {
        return tel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.tel2
     *
     * @param tel2 the value for Personnel.tel2
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setTel2(String tel2) {
        this.tel2 = tel2 == null ? null : tel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.titleCode
     *
     * @return the value of Personnel.titleCode
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getTitlecode() {
        return titlecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.titleCode
     *
     * @param titlecode the value for Personnel.titleCode
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setTitlecode(String titlecode) {
        this.titlecode = titlecode == null ? null : titlecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.titleName
     *
     * @return the value of Personnel.titleName
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getTitlename() {
        return titlename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.titleName
     *
     * @param titlename the value for Personnel.titleName
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setTitlename(String titlename) {
        this.titlename = titlename == null ? null : titlename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.email1
     *
     * @return the value of Personnel.email1
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getEmail1() {
        return email1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.email1
     *
     * @param email1 the value for Personnel.email1
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setEmail1(String email1) {
        this.email1 = email1 == null ? null : email1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.email2
     *
     * @return the value of Personnel.email2
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getEmail2() {
        return email2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.email2
     *
     * @param email2 the value for Personnel.email2
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setEmail2(String email2) {
        this.email2 = email2 == null ? null : email2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.email3
     *
     * @return the value of Personnel.email3
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getEmail3() {
        return email3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.email3
     *
     * @param email3 the value for Personnel.email3
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setEmail3(String email3) {
        this.email3 = email3 == null ? null : email3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.password
     *
     * @return the value of Personnel.password
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.password
     *
     * @param password the value for Personnel.password
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.enabled
     *
     * @return the value of Personnel.enabled
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public Byte getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.enabled
     *
     * @param enabled the value for Personnel.enabled
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setEnabled(Byte enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.eaccount
     *
     * @return the value of Personnel.eaccount
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getEaccount() {
        return eaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.eaccount
     *
     * @param eaccount the value for Personnel.eaccount
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setEaccount(String eaccount) {
        this.eaccount = eaccount == null ? null : eaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.mobile
     *
     * @return the value of Personnel.mobile
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.mobile
     *
     * @param mobile the value for Personnel.mobile
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.startDate
     *
     * @return the value of Personnel.startDate
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.startDate
     *
     * @param startdate the value for Personnel.startDate
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.endDate
     *
     * @return the value of Personnel.endDate
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.endDate
     *
     * @param enddate the value for Personnel.endDate
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.loginIP
     *
     * @return the value of Personnel.loginIP
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getLoginip() {
        return loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.loginIP
     *
     * @param loginip the value for Personnel.loginIP
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setLoginip(String loginip) {
        this.loginip = loginip == null ? null : loginip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.ssoKey
     *
     * @return the value of Personnel.ssoKey
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getSsokey() {
        return ssokey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.ssoKey
     *
     * @param ssokey the value for Personnel.ssoKey
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setSsokey(String ssokey) {
        this.ssokey = ssokey == null ? null : ssokey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.informEmail1
     *
     * @return the value of Personnel.informEmail1
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getInformemail1() {
        return informemail1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.informEmail1
     *
     * @param informemail1 the value for Personnel.informEmail1
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setInformemail1(String informemail1) {
        this.informemail1 = informemail1 == null ? null : informemail1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.informEmail2
     *
     * @return the value of Personnel.informEmail2
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getInformemail2() {
        return informemail2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.informEmail2
     *
     * @param informemail2 the value for Personnel.informEmail2
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setInformemail2(String informemail2) {
        this.informemail2 = informemail2 == null ? null : informemail2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.informMobile
     *
     * @return the value of Personnel.informMobile
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getInformmobile() {
        return informmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.informMobile
     *
     * @param informmobile the value for Personnel.informMobile
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setInformmobile(String informmobile) {
        this.informmobile = informmobile == null ? null : informmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.bkIdNum
     *
     * @return the value of Personnel.bkIdNum
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getBkidnum() {
        return bkidnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.bkIdNum
     *
     * @param bkidnum the value for Personnel.bkIdNum
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setBkidnum(String bkidnum) {
        this.bkidnum = bkidnum == null ? null : bkidnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.pid
     *
     * @return the value of Personnel.pid
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.pid
     *
     * @param pid the value for Personnel.pid
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.groupNum
     *
     * @return the value of Personnel.groupNum
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public Integer getGroupnum() {
        return groupnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.groupNum
     *
     * @param groupnum the value for Personnel.groupNum
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setGroupnum(Integer groupnum) {
        this.groupnum = groupnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.isChangPwd
     *
     * @return the value of Personnel.isChangPwd
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getIschangpwd() {
        return ischangpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.isChangPwd
     *
     * @param ischangpwd the value for Personnel.isChangPwd
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setIschangpwd(String ischangpwd) {
        this.ischangpwd = ischangpwd == null ? null : ischangpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.T_CREATEDATE
     *
     * @return the value of Personnel.T_CREATEDATE
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public Date gettCreatedate() {
        return tCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.T_CREATEDATE
     *
     * @param tCreatedate the value for Personnel.T_CREATEDATE
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void settCreatedate(Date tCreatedate) {
        this.tCreatedate = tCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.isNew
     *
     * @return the value of Personnel.isNew
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String getIsnew() {
        return isnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.isNew
     *
     * @param isnew the value for Personnel.isNew
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void setIsnew(String isnew) {
        this.isnew = isnew == null ? null : isnew.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.t_APModifyDate
     *
     * @return the value of Personnel.t_APModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public Date gettApmodifydate() {
        return tApmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.t_APModifyDate
     *
     * @param tApmodifydate the value for Personnel.t_APModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void settApmodifydate(Date tApmodifydate) {
        this.tApmodifydate = tApmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.t_APMotifier
     *
     * @return the value of Personnel.t_APMotifier
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String gettApmotifier() {
        return tApmotifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.t_APMotifier
     *
     * @param tApmotifier the value for Personnel.t_APMotifier
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void settApmotifier(String tApmotifier) {
        this.tApmotifier = tApmotifier == null ? null : tApmotifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.t_APMotifierIP
     *
     * @return the value of Personnel.t_APMotifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String gettApmotifierip() {
        return tApmotifierip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.t_APMotifierIP
     *
     * @param tApmotifierip the value for Personnel.t_APMotifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void settApmotifierip(String tApmotifierip) {
        this.tApmotifierip = tApmotifierip == null ? null : tApmotifierip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.t_ReceiveDate
     *
     * @return the value of Personnel.t_ReceiveDate
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public Date gettReceivedate() {
        return tReceivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.t_ReceiveDate
     *
     * @param tReceivedate the value for Personnel.t_ReceiveDate
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void settReceivedate(Date tReceivedate) {
        this.tReceivedate = tReceivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.t_ReceiveSystem
     *
     * @return the value of Personnel.t_ReceiveSystem
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String gettReceivesystem() {
        return tReceivesystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.t_ReceiveSystem
     *
     * @param tReceivesystem the value for Personnel.t_ReceiveSystem
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void settReceivesystem(String tReceivesystem) {
        this.tReceivesystem = tReceivesystem == null ? null : tReceivesystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.t_Creator
     *
     * @return the value of Personnel.t_Creator
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String gettCreator() {
        return tCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.t_Creator
     *
     * @param tCreator the value for Personnel.t_Creator
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void settCreator(String tCreator) {
        this.tCreator = tCreator == null ? null : tCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.t_CreatorIP
     *
     * @return the value of Personnel.t_CreatorIP
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String gettCreatorip() {
        return tCreatorip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.t_CreatorIP
     *
     * @param tCreatorip the value for Personnel.t_CreatorIP
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void settCreatorip(String tCreatorip) {
        this.tCreatorip = tCreatorip == null ? null : tCreatorip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.t_ModifyDate
     *
     * @return the value of Personnel.t_ModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public Date gettModifydate() {
        return tModifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.t_ModifyDate
     *
     * @param tModifydate the value for Personnel.t_ModifyDate
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void settModifydate(Date tModifydate) {
        this.tModifydate = tModifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.t_Modifier
     *
     * @return the value of Personnel.t_Modifier
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String gettModifier() {
        return tModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.t_Modifier
     *
     * @param tModifier the value for Personnel.t_Modifier
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void settModifier(String tModifier) {
        this.tModifier = tModifier == null ? null : tModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Personnel.t_ModifierIP
     *
     * @return the value of Personnel.t_ModifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public String gettModifierip() {
        return tModifierip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Personnel.t_ModifierIP
     *
     * @param tModifierip the value for Personnel.t_ModifierIP
     *
     * @mbg.generated Mon Apr 28 12:01:19 CST 2025
     */
    public void settModifierip(String tModifierip) {
        this.tModifierip = tModifierip == null ? null : tModifierip.trim();
    }
    
    private boolean isManager;

	public boolean isManager() {
		return isManager;
	}

	public void setManager(boolean isManager) {
		this.isManager = isManager;
	}
	
	private boolean isCredentialsExpired;

	public boolean isCredentialsExpired() {
		return isCredentialsExpired;
	}

	public void setCredentialsExpired(boolean isCredentialsExpired) {
		this.isCredentialsExpired = isCredentialsExpired;
	}
	
	
    
}